// This file is auto-generated by @hey-api/openapi-ts
import { client as _heyApiClient } from './client.gen';
import type {
  CreateDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData,
  CreateDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
  CreateDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
  CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData,
  CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
  CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
  CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData,
  CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
  CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
  DeleteDnsNetworkingMiloapisComV1Alpha1CollectionDnsZoneClassData,
  DeleteDnsNetworkingMiloapisComV1Alpha1CollectionDnsZoneClassErrors,
  DeleteDnsNetworkingMiloapisComV1Alpha1CollectionDnsZoneClassResponses,
  DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsRecordSetData,
  DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsRecordSetErrors,
  DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsRecordSetResponses,
  DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsZoneData,
  DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsZoneErrors,
  DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsZoneResponses,
  DeleteDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData,
  DeleteDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
  DeleteDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
  DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData,
  DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
  DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
  DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData,
  DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
  DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
  ListDnsNetworkingMiloapisComV1Alpha1DnsRecordSetForAllNamespacesData,
  ListDnsNetworkingMiloapisComV1Alpha1DnsRecordSetForAllNamespacesErrors,
  ListDnsNetworkingMiloapisComV1Alpha1DnsRecordSetForAllNamespacesResponses,
  ListDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData,
  ListDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
  ListDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
  ListDnsNetworkingMiloapisComV1Alpha1DnsZoneForAllNamespacesData,
  ListDnsNetworkingMiloapisComV1Alpha1DnsZoneForAllNamespacesErrors,
  ListDnsNetworkingMiloapisComV1Alpha1DnsZoneForAllNamespacesResponses,
  ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData,
  ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
  ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
  ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData,
  ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
  ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
  PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData,
  PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
  PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
  PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusData,
  PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusErrors,
  PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusResponses,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusData,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusErrors,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusResponses,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusData,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusErrors,
  PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusResponses,
  ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData,
  ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
  ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
  ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusData,
  ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusErrors,
  ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusResponses,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusData,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusErrors,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusResponses,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusData,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusErrors,
  ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusResponses,
  ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData,
  ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
  ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
  ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusData,
  ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusErrors,
  ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusResponses,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusData,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusErrors,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusResponses,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusData,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusErrors,
  ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusResponses,
} from './types.gen';
import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * list objects of kind DNSRecordSet
 */
export const listDnsNetworkingMiloapisComV1Alpha1DnsRecordSetForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListDnsNetworkingMiloapisComV1Alpha1DnsRecordSetForAllNamespacesData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDnsNetworkingMiloapisComV1Alpha1DnsRecordSetForAllNamespacesResponses,
    ListDnsNetworkingMiloapisComV1Alpha1DnsRecordSetForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnsrecordsets',
    ...options,
  });
};

/**
 * delete collection of DNSZoneClass
 */
export const deleteDnsNetworkingMiloapisComV1Alpha1CollectionDnsZoneClass = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteDnsNetworkingMiloapisComV1Alpha1CollectionDnsZoneClassData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).delete<
    DeleteDnsNetworkingMiloapisComV1Alpha1CollectionDnsZoneClassResponses,
    DeleteDnsNetworkingMiloapisComV1Alpha1CollectionDnsZoneClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnszoneclasses',
    ...options,
  });
};

/**
 * list objects of kind DNSZoneClass
 */
export const listDnsNetworkingMiloapisComV1Alpha1DnsZoneClass = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
    ListDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnszoneclasses',
    ...options,
  });
};

/**
 * create a DNSZoneClass
 */
export const createDnsNetworkingMiloapisComV1Alpha1DnsZoneClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    CreateDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
    CreateDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnszoneclasses',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a DNSZoneClass
 */
export const deleteDnsNetworkingMiloapisComV1Alpha1DnsZoneClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).delete<
    DeleteDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
    DeleteDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnszoneclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified DNSZoneClass
 */
export const readDnsNetworkingMiloapisComV1Alpha1DnsZoneClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
    ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnszoneclasses/{name}',
    ...options,
  });
};

/**
 * partially update the specified DNSZoneClass
 */
export const patchDnsNetworkingMiloapisComV1Alpha1DnsZoneClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).patch<
    PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
    PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnszoneclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified DNSZoneClass
 */
export const replaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).put<
    ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassResponses,
    ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnszoneclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified DNSZoneClass
 */
export const readDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusResponses,
    ReadDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnszoneclasses/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified DNSZoneClass
 */
export const patchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).patch<
    PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusResponses,
    PatchDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnszoneclasses/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified DNSZoneClass
 */
export const replaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).put<
    ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusResponses,
    ReplaceDnsNetworkingMiloapisComV1Alpha1DnsZoneClassStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnszoneclasses/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * list objects of kind DNSZone
 */
export const listDnsNetworkingMiloapisComV1Alpha1DnsZoneForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListDnsNetworkingMiloapisComV1Alpha1DnsZoneForAllNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDnsNetworkingMiloapisComV1Alpha1DnsZoneForAllNamespacesResponses,
    ListDnsNetworkingMiloapisComV1Alpha1DnsZoneForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/dnszones',
    ...options,
  });
};

/**
 * delete collection of DNSRecordSet
 */
export const deleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsRecordSet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsRecordSetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).delete<
    DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsRecordSetResponses,
    DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsRecordSetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnsrecordsets',
    ...options,
  });
};

/**
 * list objects of kind DNSRecordSet
 */
export const listDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
    ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnsrecordsets',
    ...options,
  });
};

/**
 * create a DNSRecordSet
 */
export const createDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
    CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnsrecordsets',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a DNSRecordSet
 */
export const deleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).delete<
    DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
    DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnsrecordsets/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified DNSRecordSet
 */
export const readDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
    ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnsrecordsets/{name}',
    ...options,
  });
};

/**
 * partially update the specified DNSRecordSet
 */
export const patchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).patch<
    PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
    PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnsrecordsets/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified DNSRecordSet
 */
export const replaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).put<
    ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetResponses,
    ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnsrecordsets/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified DNSRecordSet
 */
export const readDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusResponses,
    ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnsrecordsets/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified DNSRecordSet
 */
export const patchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).patch<
    PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusResponses,
    PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnsrecordsets/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified DNSRecordSet
 */
export const replaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).put<
    ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusResponses,
    ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsRecordSetStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnsrecordsets/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of DNSZone
 */
export const deleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsZone = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsZoneData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).delete<
    DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsZoneResponses,
    DeleteDnsNetworkingMiloapisComV1Alpha1CollectionNamespacedDnsZoneErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnszones',
    ...options,
  });
};

/**
 * list objects of kind DNSZone
 */
export const listDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZone = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
    ListDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnszones',
    ...options,
  });
};

/**
 * create a DNSZone
 */
export const createDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZone = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
    CreateDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnszones',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a DNSZone
 */
export const deleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZone = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).delete<
    DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
    DeleteDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnszones/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified DNSZone
 */
export const readDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZone = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
    ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnszones/{name}',
    ...options,
  });
};

/**
 * partially update the specified DNSZone
 */
export const patchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZone = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).patch<
    PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
    PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnszones/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified DNSZone
 */
export const replaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZone = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).put<
    ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneResponses,
    ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnszones/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified DNSZone
 */
export const readDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusResponses,
    ReadDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnszones/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified DNSZone
 */
export const patchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).patch<
    PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusResponses,
    PatchDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnszones/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified DNSZone
 */
export const replaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).put<
    ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusResponses,
    ReplaceDnsNetworkingMiloapisComV1Alpha1NamespacedDnsZoneStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/dns.networking.miloapis.com/v1alpha1/namespaces/{namespace}/dnszones/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
