// This file is auto-generated by @hey-api/openapi-ts
import type { Options as ClientOptions, TDataShape, Client } from '../shared/client';
import { client } from '../shared/client.gen';
import type {
  ListIamMiloapisComV1Alpha1GroupMembershipForAllNamespacesData,
  ListIamMiloapisComV1Alpha1GroupMembershipForAllNamespacesResponses,
  ListIamMiloapisComV1Alpha1GroupMembershipForAllNamespacesErrors,
  ListIamMiloapisComV1Alpha1GroupForAllNamespacesData,
  ListIamMiloapisComV1Alpha1GroupForAllNamespacesResponses,
  ListIamMiloapisComV1Alpha1GroupForAllNamespacesErrors,
  ListIamMiloapisComV1Alpha1MachineAccountKeyForAllNamespacesData,
  ListIamMiloapisComV1Alpha1MachineAccountKeyForAllNamespacesResponses,
  ListIamMiloapisComV1Alpha1MachineAccountKeyForAllNamespacesErrors,
  ListIamMiloapisComV1Alpha1MachineAccountForAllNamespacesData,
  ListIamMiloapisComV1Alpha1MachineAccountForAllNamespacesResponses,
  ListIamMiloapisComV1Alpha1MachineAccountForAllNamespacesErrors,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupMembershipData,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupMembershipResponses,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupMembershipErrors,
  ListIamMiloapisComV1Alpha1NamespacedGroupMembershipData,
  ListIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
  ListIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
  CreateIamMiloapisComV1Alpha1NamespacedGroupMembershipData,
  CreateIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
  CreateIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
  DeleteIamMiloapisComV1Alpha1NamespacedGroupMembershipData,
  DeleteIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
  DeleteIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
  ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipData,
  ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
  ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
  PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipData,
  PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
  PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipData,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
  ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusData,
  ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusResponses,
  ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusErrors,
  PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusData,
  PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusResponses,
  PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusData,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusErrors,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupData,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupResponses,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupErrors,
  ListIamMiloapisComV1Alpha1NamespacedGroupData,
  ListIamMiloapisComV1Alpha1NamespacedGroupResponses,
  ListIamMiloapisComV1Alpha1NamespacedGroupErrors,
  CreateIamMiloapisComV1Alpha1NamespacedGroupData,
  CreateIamMiloapisComV1Alpha1NamespacedGroupResponses,
  CreateIamMiloapisComV1Alpha1NamespacedGroupErrors,
  DeleteIamMiloapisComV1Alpha1NamespacedGroupData,
  DeleteIamMiloapisComV1Alpha1NamespacedGroupResponses,
  DeleteIamMiloapisComV1Alpha1NamespacedGroupErrors,
  ReadIamMiloapisComV1Alpha1NamespacedGroupData,
  ReadIamMiloapisComV1Alpha1NamespacedGroupResponses,
  ReadIamMiloapisComV1Alpha1NamespacedGroupErrors,
  PatchIamMiloapisComV1Alpha1NamespacedGroupData,
  PatchIamMiloapisComV1Alpha1NamespacedGroupResponses,
  PatchIamMiloapisComV1Alpha1NamespacedGroupErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupData,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupErrors,
  ReadIamMiloapisComV1Alpha1NamespacedGroupStatusData,
  ReadIamMiloapisComV1Alpha1NamespacedGroupStatusResponses,
  ReadIamMiloapisComV1Alpha1NamespacedGroupStatusErrors,
  PatchIamMiloapisComV1Alpha1NamespacedGroupStatusData,
  PatchIamMiloapisComV1Alpha1NamespacedGroupStatusResponses,
  PatchIamMiloapisComV1Alpha1NamespacedGroupStatusErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupStatusData,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupStatusResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedGroupStatusErrors,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountKeyData,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountKeyResponses,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountKeyErrors,
  ListIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData,
  ListIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
  ListIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
  CreateIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData,
  CreateIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
  CreateIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
  DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData,
  DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
  DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusData,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusResponses,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusErrors,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusData,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusResponses,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusData,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusErrors,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountData,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountResponses,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountErrors,
  ListIamMiloapisComV1Alpha1NamespacedMachineAccountData,
  ListIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
  ListIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
  CreateIamMiloapisComV1Alpha1NamespacedMachineAccountData,
  CreateIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
  CreateIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
  DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountData,
  DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
  DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountData,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountData,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountData,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountStatusData,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountStatusResponses,
  ReadIamMiloapisComV1Alpha1NamespacedMachineAccountStatusErrors,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountStatusData,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountStatusResponses,
  PatchIamMiloapisComV1Alpha1NamespacedMachineAccountStatusErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountStatusData,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountStatusResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountStatusErrors,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedPolicyBindingData,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedPolicyBindingResponses,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedPolicyBindingErrors,
  ListIamMiloapisComV1Alpha1NamespacedPolicyBindingData,
  ListIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
  ListIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
  CreateIamMiloapisComV1Alpha1NamespacedPolicyBindingData,
  CreateIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
  CreateIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
  DeleteIamMiloapisComV1Alpha1NamespacedPolicyBindingData,
  DeleteIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
  DeleteIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
  ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingData,
  ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
  ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
  PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingData,
  PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
  PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingData,
  ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
  ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusData,
  ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusResponses,
  ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusErrors,
  PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusData,
  PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusResponses,
  PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusData,
  ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusErrors,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedRoleData,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedRoleResponses,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedRoleErrors,
  ListIamMiloapisComV1Alpha1NamespacedRoleData,
  ListIamMiloapisComV1Alpha1NamespacedRoleResponses,
  ListIamMiloapisComV1Alpha1NamespacedRoleErrors,
  CreateIamMiloapisComV1Alpha1NamespacedRoleData,
  CreateIamMiloapisComV1Alpha1NamespacedRoleResponses,
  CreateIamMiloapisComV1Alpha1NamespacedRoleErrors,
  DeleteIamMiloapisComV1Alpha1NamespacedRoleData,
  DeleteIamMiloapisComV1Alpha1NamespacedRoleResponses,
  DeleteIamMiloapisComV1Alpha1NamespacedRoleErrors,
  ReadIamMiloapisComV1Alpha1NamespacedRoleData,
  ReadIamMiloapisComV1Alpha1NamespacedRoleResponses,
  ReadIamMiloapisComV1Alpha1NamespacedRoleErrors,
  PatchIamMiloapisComV1Alpha1NamespacedRoleData,
  PatchIamMiloapisComV1Alpha1NamespacedRoleResponses,
  PatchIamMiloapisComV1Alpha1NamespacedRoleErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedRoleData,
  ReplaceIamMiloapisComV1Alpha1NamespacedRoleResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedRoleErrors,
  ReadIamMiloapisComV1Alpha1NamespacedRoleStatusData,
  ReadIamMiloapisComV1Alpha1NamespacedRoleStatusResponses,
  ReadIamMiloapisComV1Alpha1NamespacedRoleStatusErrors,
  PatchIamMiloapisComV1Alpha1NamespacedRoleStatusData,
  PatchIamMiloapisComV1Alpha1NamespacedRoleStatusResponses,
  PatchIamMiloapisComV1Alpha1NamespacedRoleStatusErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedRoleStatusData,
  ReplaceIamMiloapisComV1Alpha1NamespacedRoleStatusResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedRoleStatusErrors,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedUserInvitationData,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedUserInvitationResponses,
  DeleteIamMiloapisComV1Alpha1CollectionNamespacedUserInvitationErrors,
  ListIamMiloapisComV1Alpha1NamespacedUserInvitationData,
  ListIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
  ListIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
  CreateIamMiloapisComV1Alpha1NamespacedUserInvitationData,
  CreateIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
  CreateIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
  DeleteIamMiloapisComV1Alpha1NamespacedUserInvitationData,
  DeleteIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
  DeleteIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
  ReadIamMiloapisComV1Alpha1NamespacedUserInvitationData,
  ReadIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
  ReadIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
  PatchIamMiloapisComV1Alpha1NamespacedUserInvitationData,
  PatchIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
  PatchIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationData,
  ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
  ReadIamMiloapisComV1Alpha1NamespacedUserInvitationStatusData,
  ReadIamMiloapisComV1Alpha1NamespacedUserInvitationStatusResponses,
  ReadIamMiloapisComV1Alpha1NamespacedUserInvitationStatusErrors,
  PatchIamMiloapisComV1Alpha1NamespacedUserInvitationStatusData,
  PatchIamMiloapisComV1Alpha1NamespacedUserInvitationStatusResponses,
  PatchIamMiloapisComV1Alpha1NamespacedUserInvitationStatusErrors,
  ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationStatusData,
  ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationStatusResponses,
  ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationStatusErrors,
  ListIamMiloapisComV1Alpha1PolicyBindingForAllNamespacesData,
  ListIamMiloapisComV1Alpha1PolicyBindingForAllNamespacesResponses,
  ListIamMiloapisComV1Alpha1PolicyBindingForAllNamespacesErrors,
  DeleteIamMiloapisComV1Alpha1CollectionProtectedResourceData,
  DeleteIamMiloapisComV1Alpha1CollectionProtectedResourceResponses,
  DeleteIamMiloapisComV1Alpha1CollectionProtectedResourceErrors,
  ListIamMiloapisComV1Alpha1ProtectedResourceData,
  ListIamMiloapisComV1Alpha1ProtectedResourceResponses,
  ListIamMiloapisComV1Alpha1ProtectedResourceErrors,
  CreateIamMiloapisComV1Alpha1ProtectedResourceData,
  CreateIamMiloapisComV1Alpha1ProtectedResourceResponses,
  CreateIamMiloapisComV1Alpha1ProtectedResourceErrors,
  DeleteIamMiloapisComV1Alpha1ProtectedResourceData,
  DeleteIamMiloapisComV1Alpha1ProtectedResourceResponses,
  DeleteIamMiloapisComV1Alpha1ProtectedResourceErrors,
  ReadIamMiloapisComV1Alpha1ProtectedResourceData,
  ReadIamMiloapisComV1Alpha1ProtectedResourceResponses,
  ReadIamMiloapisComV1Alpha1ProtectedResourceErrors,
  PatchIamMiloapisComV1Alpha1ProtectedResourceData,
  PatchIamMiloapisComV1Alpha1ProtectedResourceResponses,
  PatchIamMiloapisComV1Alpha1ProtectedResourceErrors,
  ReplaceIamMiloapisComV1Alpha1ProtectedResourceData,
  ReplaceIamMiloapisComV1Alpha1ProtectedResourceResponses,
  ReplaceIamMiloapisComV1Alpha1ProtectedResourceErrors,
  ReadIamMiloapisComV1Alpha1ProtectedResourceStatusData,
  ReadIamMiloapisComV1Alpha1ProtectedResourceStatusResponses,
  ReadIamMiloapisComV1Alpha1ProtectedResourceStatusErrors,
  PatchIamMiloapisComV1Alpha1ProtectedResourceStatusData,
  PatchIamMiloapisComV1Alpha1ProtectedResourceStatusResponses,
  PatchIamMiloapisComV1Alpha1ProtectedResourceStatusErrors,
  ReplaceIamMiloapisComV1Alpha1ProtectedResourceStatusData,
  ReplaceIamMiloapisComV1Alpha1ProtectedResourceStatusResponses,
  ReplaceIamMiloapisComV1Alpha1ProtectedResourceStatusErrors,
  ListIamMiloapisComV1Alpha1RoleForAllNamespacesData,
  ListIamMiloapisComV1Alpha1RoleForAllNamespacesResponses,
  ListIamMiloapisComV1Alpha1RoleForAllNamespacesErrors,
  DeleteIamMiloapisComV1Alpha1CollectionUserDeactivationData,
  DeleteIamMiloapisComV1Alpha1CollectionUserDeactivationResponses,
  DeleteIamMiloapisComV1Alpha1CollectionUserDeactivationErrors,
  ListIamMiloapisComV1Alpha1UserDeactivationData,
  ListIamMiloapisComV1Alpha1UserDeactivationResponses,
  ListIamMiloapisComV1Alpha1UserDeactivationErrors,
  CreateIamMiloapisComV1Alpha1UserDeactivationData,
  CreateIamMiloapisComV1Alpha1UserDeactivationResponses,
  CreateIamMiloapisComV1Alpha1UserDeactivationErrors,
  DeleteIamMiloapisComV1Alpha1UserDeactivationData,
  DeleteIamMiloapisComV1Alpha1UserDeactivationResponses,
  DeleteIamMiloapisComV1Alpha1UserDeactivationErrors,
  ReadIamMiloapisComV1Alpha1UserDeactivationData,
  ReadIamMiloapisComV1Alpha1UserDeactivationResponses,
  ReadIamMiloapisComV1Alpha1UserDeactivationErrors,
  PatchIamMiloapisComV1Alpha1UserDeactivationData,
  PatchIamMiloapisComV1Alpha1UserDeactivationResponses,
  PatchIamMiloapisComV1Alpha1UserDeactivationErrors,
  ReplaceIamMiloapisComV1Alpha1UserDeactivationData,
  ReplaceIamMiloapisComV1Alpha1UserDeactivationResponses,
  ReplaceIamMiloapisComV1Alpha1UserDeactivationErrors,
  ReadIamMiloapisComV1Alpha1UserDeactivationStatusData,
  ReadIamMiloapisComV1Alpha1UserDeactivationStatusResponses,
  ReadIamMiloapisComV1Alpha1UserDeactivationStatusErrors,
  PatchIamMiloapisComV1Alpha1UserDeactivationStatusData,
  PatchIamMiloapisComV1Alpha1UserDeactivationStatusResponses,
  PatchIamMiloapisComV1Alpha1UserDeactivationStatusErrors,
  ReplaceIamMiloapisComV1Alpha1UserDeactivationStatusData,
  ReplaceIamMiloapisComV1Alpha1UserDeactivationStatusResponses,
  ReplaceIamMiloapisComV1Alpha1UserDeactivationStatusErrors,
  ListIamMiloapisComV1Alpha1UserInvitationForAllNamespacesData,
  ListIamMiloapisComV1Alpha1UserInvitationForAllNamespacesResponses,
  ListIamMiloapisComV1Alpha1UserInvitationForAllNamespacesErrors,
  DeleteIamMiloapisComV1Alpha1CollectionUserPreferenceData,
  DeleteIamMiloapisComV1Alpha1CollectionUserPreferenceResponses,
  DeleteIamMiloapisComV1Alpha1CollectionUserPreferenceErrors,
  ListIamMiloapisComV1Alpha1UserPreferenceData,
  ListIamMiloapisComV1Alpha1UserPreferenceResponses,
  ListIamMiloapisComV1Alpha1UserPreferenceErrors,
  CreateIamMiloapisComV1Alpha1UserPreferenceData,
  CreateIamMiloapisComV1Alpha1UserPreferenceResponses,
  CreateIamMiloapisComV1Alpha1UserPreferenceErrors,
  DeleteIamMiloapisComV1Alpha1UserPreferenceData,
  DeleteIamMiloapisComV1Alpha1UserPreferenceResponses,
  DeleteIamMiloapisComV1Alpha1UserPreferenceErrors,
  ReadIamMiloapisComV1Alpha1UserPreferenceData,
  ReadIamMiloapisComV1Alpha1UserPreferenceResponses,
  ReadIamMiloapisComV1Alpha1UserPreferenceErrors,
  PatchIamMiloapisComV1Alpha1UserPreferenceData,
  PatchIamMiloapisComV1Alpha1UserPreferenceResponses,
  PatchIamMiloapisComV1Alpha1UserPreferenceErrors,
  ReplaceIamMiloapisComV1Alpha1UserPreferenceData,
  ReplaceIamMiloapisComV1Alpha1UserPreferenceResponses,
  ReplaceIamMiloapisComV1Alpha1UserPreferenceErrors,
  ReadIamMiloapisComV1Alpha1UserPreferenceStatusData,
  ReadIamMiloapisComV1Alpha1UserPreferenceStatusResponses,
  ReadIamMiloapisComV1Alpha1UserPreferenceStatusErrors,
  PatchIamMiloapisComV1Alpha1UserPreferenceStatusData,
  PatchIamMiloapisComV1Alpha1UserPreferenceStatusResponses,
  PatchIamMiloapisComV1Alpha1UserPreferenceStatusErrors,
  ReplaceIamMiloapisComV1Alpha1UserPreferenceStatusData,
  ReplaceIamMiloapisComV1Alpha1UserPreferenceStatusResponses,
  ReplaceIamMiloapisComV1Alpha1UserPreferenceStatusErrors,
  DeleteIamMiloapisComV1Alpha1CollectionUserData,
  DeleteIamMiloapisComV1Alpha1CollectionUserResponses,
  DeleteIamMiloapisComV1Alpha1CollectionUserErrors,
  ListIamMiloapisComV1Alpha1UserData,
  ListIamMiloapisComV1Alpha1UserResponses,
  ListIamMiloapisComV1Alpha1UserErrors,
  CreateIamMiloapisComV1Alpha1UserData,
  CreateIamMiloapisComV1Alpha1UserResponses,
  CreateIamMiloapisComV1Alpha1UserErrors,
  DeleteIamMiloapisComV1Alpha1UserData,
  DeleteIamMiloapisComV1Alpha1UserResponses,
  DeleteIamMiloapisComV1Alpha1UserErrors,
  ReadIamMiloapisComV1Alpha1UserData,
  ReadIamMiloapisComV1Alpha1UserResponses,
  ReadIamMiloapisComV1Alpha1UserErrors,
  PatchIamMiloapisComV1Alpha1UserData,
  PatchIamMiloapisComV1Alpha1UserResponses,
  PatchIamMiloapisComV1Alpha1UserErrors,
  ReplaceIamMiloapisComV1Alpha1UserData,
  ReplaceIamMiloapisComV1Alpha1UserResponses,
  ReplaceIamMiloapisComV1Alpha1UserErrors,
  ReadIamMiloapisComV1Alpha1UserStatusData,
  ReadIamMiloapisComV1Alpha1UserStatusResponses,
  ReadIamMiloapisComV1Alpha1UserStatusErrors,
  PatchIamMiloapisComV1Alpha1UserStatusData,
  PatchIamMiloapisComV1Alpha1UserStatusResponses,
  PatchIamMiloapisComV1Alpha1UserStatusErrors,
  ReplaceIamMiloapisComV1Alpha1UserStatusData,
  ReplaceIamMiloapisComV1Alpha1UserStatusResponses,
  ReplaceIamMiloapisComV1Alpha1UserStatusErrors,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * list objects of kind GroupMembership
 */
export const listIamMiloapisComV1Alpha1GroupMembershipForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListIamMiloapisComV1Alpha1GroupMembershipForAllNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListIamMiloapisComV1Alpha1GroupMembershipForAllNamespacesResponses,
    ListIamMiloapisComV1Alpha1GroupMembershipForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/groupmemberships',
    ...options,
  });
};

/**
 * list objects of kind Group
 */
export const listIamMiloapisComV1Alpha1GroupForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListIamMiloapisComV1Alpha1GroupForAllNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListIamMiloapisComV1Alpha1GroupForAllNamespacesResponses,
    ListIamMiloapisComV1Alpha1GroupForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/groups',
    ...options,
  });
};

/**
 * list objects of kind MachineAccountKey
 */
export const listIamMiloapisComV1Alpha1MachineAccountKeyForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListIamMiloapisComV1Alpha1MachineAccountKeyForAllNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListIamMiloapisComV1Alpha1MachineAccountKeyForAllNamespacesResponses,
    ListIamMiloapisComV1Alpha1MachineAccountKeyForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/machineaccountkeys',
    ...options,
  });
};

/**
 * list objects of kind MachineAccount
 */
export const listIamMiloapisComV1Alpha1MachineAccountForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListIamMiloapisComV1Alpha1MachineAccountForAllNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListIamMiloapisComV1Alpha1MachineAccountForAllNamespacesResponses,
    ListIamMiloapisComV1Alpha1MachineAccountForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/machineaccounts',
    ...options,
  });
};

/**
 * delete collection of GroupMembership
 */
export const deleteIamMiloapisComV1Alpha1CollectionNamespacedGroupMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupMembershipData,
    ThrowOnError
  >
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupMembershipResponses,
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groupmemberships',
    ...options,
  });
};

/**
 * list objects of kind GroupMembership
 */
export const listIamMiloapisComV1Alpha1NamespacedGroupMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListIamMiloapisComV1Alpha1NamespacedGroupMembershipData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ListIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
    ListIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groupmemberships',
    ...options,
  });
};

/**
 * create a GroupMembership
 */
export const createIamMiloapisComV1Alpha1NamespacedGroupMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateIamMiloapisComV1Alpha1NamespacedGroupMembershipData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
    CreateIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groupmemberships',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a GroupMembership
 */
export const deleteIamMiloapisComV1Alpha1NamespacedGroupMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteIamMiloapisComV1Alpha1NamespacedGroupMembershipData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
    DeleteIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groupmemberships/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified GroupMembership
 */
export const readIamMiloapisComV1Alpha1NamespacedGroupMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
    ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groupmemberships/{name}',
    ...options,
  });
};

/**
 * partially update the specified GroupMembership
 */
export const patchIamMiloapisComV1Alpha1NamespacedGroupMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
    PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groupmemberships/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified GroupMembership
 */
export const replaceIamMiloapisComV1Alpha1NamespacedGroupMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groupmemberships/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified GroupMembership
 */
export const readIamMiloapisComV1Alpha1NamespacedGroupMembershipStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusResponses,
    ReadIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groupmemberships/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified GroupMembership
 */
export const patchIamMiloapisComV1Alpha1NamespacedGroupMembershipStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusResponses,
    PatchIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groupmemberships/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified GroupMembership
 */
export const replaceIamMiloapisComV1Alpha1NamespacedGroupMembershipStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedGroupMembershipStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groupmemberships/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of Group
 */
export const deleteIamMiloapisComV1Alpha1CollectionNamespacedGroup = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupResponses,
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedGroupErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groups',
    ...options,
  });
};

/**
 * list objects of kind Group
 */
export const listIamMiloapisComV1Alpha1NamespacedGroup = <ThrowOnError extends boolean = false>(
  options: Options<ListIamMiloapisComV1Alpha1NamespacedGroupData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ListIamMiloapisComV1Alpha1NamespacedGroupResponses,
    ListIamMiloapisComV1Alpha1NamespacedGroupErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groups',
    ...options,
  });
};

/**
 * create a Group
 */
export const createIamMiloapisComV1Alpha1NamespacedGroup = <ThrowOnError extends boolean = false>(
  options: Options<CreateIamMiloapisComV1Alpha1NamespacedGroupData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateIamMiloapisComV1Alpha1NamespacedGroupResponses,
    CreateIamMiloapisComV1Alpha1NamespacedGroupErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a Group
 */
export const deleteIamMiloapisComV1Alpha1NamespacedGroup = <ThrowOnError extends boolean = false>(
  options: Options<DeleteIamMiloapisComV1Alpha1NamespacedGroupData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1NamespacedGroupResponses,
    DeleteIamMiloapisComV1Alpha1NamespacedGroupErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groups/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified Group
 */
export const readIamMiloapisComV1Alpha1NamespacedGroup = <ThrowOnError extends boolean = false>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedGroupData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedGroupResponses,
    ReadIamMiloapisComV1Alpha1NamespacedGroupErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groups/{name}',
    ...options,
  });
};

/**
 * partially update the specified Group
 */
export const patchIamMiloapisComV1Alpha1NamespacedGroup = <ThrowOnError extends boolean = false>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedGroupData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedGroupResponses,
    PatchIamMiloapisComV1Alpha1NamespacedGroupErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groups/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified Group
 */
export const replaceIamMiloapisComV1Alpha1NamespacedGroup = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedGroupData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedGroupResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedGroupErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groups/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified Group
 */
export const readIamMiloapisComV1Alpha1NamespacedGroupStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedGroupStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedGroupStatusResponses,
    ReadIamMiloapisComV1Alpha1NamespacedGroupStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groups/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified Group
 */
export const patchIamMiloapisComV1Alpha1NamespacedGroupStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedGroupStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedGroupStatusResponses,
    PatchIamMiloapisComV1Alpha1NamespacedGroupStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groups/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified Group
 */
export const replaceIamMiloapisComV1Alpha1NamespacedGroupStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedGroupStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedGroupStatusResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedGroupStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/groups/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of MachineAccountKey
 */
export const deleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountKey = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountKeyData,
    ThrowOnError
  >
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountKeyResponses,
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountKeyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccountkeys',
    ...options,
  });
};

/**
 * list objects of kind MachineAccountKey
 */
export const listIamMiloapisComV1Alpha1NamespacedMachineAccountKey = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ListIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
    ListIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccountkeys',
    ...options,
  });
};

/**
 * create a MachineAccountKey
 */
export const createIamMiloapisComV1Alpha1NamespacedMachineAccountKey = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
    CreateIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccountkeys',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a MachineAccountKey
 */
export const deleteIamMiloapisComV1Alpha1NamespacedMachineAccountKey = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
    DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccountkeys/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified MachineAccountKey
 */
export const readIamMiloapisComV1Alpha1NamespacedMachineAccountKey = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
    ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccountkeys/{name}',
    ...options,
  });
};

/**
 * partially update the specified MachineAccountKey
 */
export const patchIamMiloapisComV1Alpha1NamespacedMachineAccountKey = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
    PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccountkeys/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified MachineAccountKey
 */
export const replaceIamMiloapisComV1Alpha1NamespacedMachineAccountKey = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccountkeys/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified MachineAccountKey
 */
export const readIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusResponses,
    ReadIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccountkeys/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified MachineAccountKey
 */
export const patchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusResponses,
    PatchIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccountkeys/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified MachineAccountKey
 */
export const replaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountKeyStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccountkeys/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of MachineAccount
 */
export const deleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountResponses,
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedMachineAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccounts',
    ...options,
  });
};

/**
 * list objects of kind MachineAccount
 */
export const listIamMiloapisComV1Alpha1NamespacedMachineAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListIamMiloapisComV1Alpha1NamespacedMachineAccountData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ListIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
    ListIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccounts',
    ...options,
  });
};

/**
 * create a MachineAccount
 */
export const createIamMiloapisComV1Alpha1NamespacedMachineAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateIamMiloapisComV1Alpha1NamespacedMachineAccountData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
    CreateIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a MachineAccount
 */
export const deleteIamMiloapisComV1Alpha1NamespacedMachineAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
    DeleteIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified MachineAccount
 */
export const readIamMiloapisComV1Alpha1NamespacedMachineAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedMachineAccountData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
    ReadIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccounts/{name}',
    ...options,
  });
};

/**
 * partially update the specified MachineAccount
 */
export const patchIamMiloapisComV1Alpha1NamespacedMachineAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedMachineAccountData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
    PatchIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified MachineAccount
 */
export const replaceIamMiloapisComV1Alpha1NamespacedMachineAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified MachineAccount
 */
export const readIamMiloapisComV1Alpha1NamespacedMachineAccountStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedMachineAccountStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedMachineAccountStatusResponses,
    ReadIamMiloapisComV1Alpha1NamespacedMachineAccountStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccounts/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified MachineAccount
 */
export const patchIamMiloapisComV1Alpha1NamespacedMachineAccountStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedMachineAccountStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedMachineAccountStatusResponses,
    PatchIamMiloapisComV1Alpha1NamespacedMachineAccountStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccounts/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified MachineAccount
 */
export const replaceIamMiloapisComV1Alpha1NamespacedMachineAccountStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountStatusResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedMachineAccountStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/machineaccounts/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of PolicyBinding
 */
export const deleteIamMiloapisComV1Alpha1CollectionNamespacedPolicyBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteIamMiloapisComV1Alpha1CollectionNamespacedPolicyBindingData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedPolicyBindingResponses,
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedPolicyBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/policybindings',
    ...options,
  });
};

/**
 * list objects of kind PolicyBinding
 */
export const listIamMiloapisComV1Alpha1NamespacedPolicyBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListIamMiloapisComV1Alpha1NamespacedPolicyBindingData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ListIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
    ListIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/policybindings',
    ...options,
  });
};

/**
 * create a PolicyBinding
 */
export const createIamMiloapisComV1Alpha1NamespacedPolicyBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateIamMiloapisComV1Alpha1NamespacedPolicyBindingData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
    CreateIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/policybindings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a PolicyBinding
 */
export const deleteIamMiloapisComV1Alpha1NamespacedPolicyBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteIamMiloapisComV1Alpha1NamespacedPolicyBindingData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
    DeleteIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/policybindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified PolicyBinding
 */
export const readIamMiloapisComV1Alpha1NamespacedPolicyBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
    ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/policybindings/{name}',
    ...options,
  });
};

/**
 * partially update the specified PolicyBinding
 */
export const patchIamMiloapisComV1Alpha1NamespacedPolicyBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
    PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/policybindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified PolicyBinding
 */
export const replaceIamMiloapisComV1Alpha1NamespacedPolicyBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/policybindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified PolicyBinding
 */
export const readIamMiloapisComV1Alpha1NamespacedPolicyBindingStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusResponses,
    ReadIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/policybindings/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified PolicyBinding
 */
export const patchIamMiloapisComV1Alpha1NamespacedPolicyBindingStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusResponses,
    PatchIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/policybindings/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified PolicyBinding
 */
export const replaceIamMiloapisComV1Alpha1NamespacedPolicyBindingStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedPolicyBindingStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/policybindings/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of Role
 */
export const deleteIamMiloapisComV1Alpha1CollectionNamespacedRole = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteIamMiloapisComV1Alpha1CollectionNamespacedRoleData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedRoleResponses,
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/roles',
    ...options,
  });
};

/**
 * list objects of kind Role
 */
export const listIamMiloapisComV1Alpha1NamespacedRole = <ThrowOnError extends boolean = false>(
  options: Options<ListIamMiloapisComV1Alpha1NamespacedRoleData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ListIamMiloapisComV1Alpha1NamespacedRoleResponses,
    ListIamMiloapisComV1Alpha1NamespacedRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/roles',
    ...options,
  });
};

/**
 * create a Role
 */
export const createIamMiloapisComV1Alpha1NamespacedRole = <ThrowOnError extends boolean = false>(
  options: Options<CreateIamMiloapisComV1Alpha1NamespacedRoleData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateIamMiloapisComV1Alpha1NamespacedRoleResponses,
    CreateIamMiloapisComV1Alpha1NamespacedRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/roles',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a Role
 */
export const deleteIamMiloapisComV1Alpha1NamespacedRole = <ThrowOnError extends boolean = false>(
  options: Options<DeleteIamMiloapisComV1Alpha1NamespacedRoleData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1NamespacedRoleResponses,
    DeleteIamMiloapisComV1Alpha1NamespacedRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/roles/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified Role
 */
export const readIamMiloapisComV1Alpha1NamespacedRole = <ThrowOnError extends boolean = false>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedRoleData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedRoleResponses,
    ReadIamMiloapisComV1Alpha1NamespacedRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/roles/{name}',
    ...options,
  });
};

/**
 * partially update the specified Role
 */
export const patchIamMiloapisComV1Alpha1NamespacedRole = <ThrowOnError extends boolean = false>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedRoleData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedRoleResponses,
    PatchIamMiloapisComV1Alpha1NamespacedRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/roles/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified Role
 */
export const replaceIamMiloapisComV1Alpha1NamespacedRole = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedRoleData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedRoleResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/roles/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified Role
 */
export const readIamMiloapisComV1Alpha1NamespacedRoleStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedRoleStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedRoleStatusResponses,
    ReadIamMiloapisComV1Alpha1NamespacedRoleStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/roles/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified Role
 */
export const patchIamMiloapisComV1Alpha1NamespacedRoleStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedRoleStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedRoleStatusResponses,
    PatchIamMiloapisComV1Alpha1NamespacedRoleStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/roles/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified Role
 */
export const replaceIamMiloapisComV1Alpha1NamespacedRoleStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedRoleStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedRoleStatusResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedRoleStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/roles/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of UserInvitation
 */
export const deleteIamMiloapisComV1Alpha1CollectionNamespacedUserInvitation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteIamMiloapisComV1Alpha1CollectionNamespacedUserInvitationData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedUserInvitationResponses,
    DeleteIamMiloapisComV1Alpha1CollectionNamespacedUserInvitationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/userinvitations',
    ...options,
  });
};

/**
 * list objects of kind UserInvitation
 */
export const listIamMiloapisComV1Alpha1NamespacedUserInvitation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListIamMiloapisComV1Alpha1NamespacedUserInvitationData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ListIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
    ListIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/userinvitations',
    ...options,
  });
};

/**
 * create an UserInvitation
 */
export const createIamMiloapisComV1Alpha1NamespacedUserInvitation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateIamMiloapisComV1Alpha1NamespacedUserInvitationData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
    CreateIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/userinvitations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete an UserInvitation
 */
export const deleteIamMiloapisComV1Alpha1NamespacedUserInvitation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteIamMiloapisComV1Alpha1NamespacedUserInvitationData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
    DeleteIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/userinvitations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified UserInvitation
 */
export const readIamMiloapisComV1Alpha1NamespacedUserInvitation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedUserInvitationData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
    ReadIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/userinvitations/{name}',
    ...options,
  });
};

/**
 * partially update the specified UserInvitation
 */
export const patchIamMiloapisComV1Alpha1NamespacedUserInvitation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedUserInvitationData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
    PatchIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/userinvitations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified UserInvitation
 */
export const replaceIamMiloapisComV1Alpha1NamespacedUserInvitation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/userinvitations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified UserInvitation
 */
export const readIamMiloapisComV1Alpha1NamespacedUserInvitationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1NamespacedUserInvitationStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1NamespacedUserInvitationStatusResponses,
    ReadIamMiloapisComV1Alpha1NamespacedUserInvitationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/userinvitations/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified UserInvitation
 */
export const patchIamMiloapisComV1Alpha1NamespacedUserInvitationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1NamespacedUserInvitationStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1NamespacedUserInvitationStatusResponses,
    PatchIamMiloapisComV1Alpha1NamespacedUserInvitationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/userinvitations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified UserInvitation
 */
export const replaceIamMiloapisComV1Alpha1NamespacedUserInvitationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationStatusResponses,
    ReplaceIamMiloapisComV1Alpha1NamespacedUserInvitationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/namespaces/{namespace}/userinvitations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * list objects of kind PolicyBinding
 */
export const listIamMiloapisComV1Alpha1PolicyBindingForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListIamMiloapisComV1Alpha1PolicyBindingForAllNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListIamMiloapisComV1Alpha1PolicyBindingForAllNamespacesResponses,
    ListIamMiloapisComV1Alpha1PolicyBindingForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/policybindings',
    ...options,
  });
};

/**
 * delete collection of ProtectedResource
 */
export const deleteIamMiloapisComV1Alpha1CollectionProtectedResource = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteIamMiloapisComV1Alpha1CollectionProtectedResourceData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1CollectionProtectedResourceResponses,
    DeleteIamMiloapisComV1Alpha1CollectionProtectedResourceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/protectedresources',
    ...options,
  });
};

/**
 * list objects of kind ProtectedResource
 */
export const listIamMiloapisComV1Alpha1ProtectedResource = <ThrowOnError extends boolean = false>(
  options?: Options<ListIamMiloapisComV1Alpha1ProtectedResourceData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListIamMiloapisComV1Alpha1ProtectedResourceResponses,
    ListIamMiloapisComV1Alpha1ProtectedResourceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/protectedresources',
    ...options,
  });
};

/**
 * create a ProtectedResource
 */
export const createIamMiloapisComV1Alpha1ProtectedResource = <ThrowOnError extends boolean = false>(
  options: Options<CreateIamMiloapisComV1Alpha1ProtectedResourceData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateIamMiloapisComV1Alpha1ProtectedResourceResponses,
    CreateIamMiloapisComV1Alpha1ProtectedResourceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/protectedresources',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a ProtectedResource
 */
export const deleteIamMiloapisComV1Alpha1ProtectedResource = <ThrowOnError extends boolean = false>(
  options: Options<DeleteIamMiloapisComV1Alpha1ProtectedResourceData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1ProtectedResourceResponses,
    DeleteIamMiloapisComV1Alpha1ProtectedResourceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/protectedresources/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified ProtectedResource
 */
export const readIamMiloapisComV1Alpha1ProtectedResource = <ThrowOnError extends boolean = false>(
  options: Options<ReadIamMiloapisComV1Alpha1ProtectedResourceData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1ProtectedResourceResponses,
    ReadIamMiloapisComV1Alpha1ProtectedResourceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/protectedresources/{name}',
    ...options,
  });
};

/**
 * partially update the specified ProtectedResource
 */
export const patchIamMiloapisComV1Alpha1ProtectedResource = <ThrowOnError extends boolean = false>(
  options: Options<PatchIamMiloapisComV1Alpha1ProtectedResourceData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1ProtectedResourceResponses,
    PatchIamMiloapisComV1Alpha1ProtectedResourceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/protectedresources/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified ProtectedResource
 */
export const replaceIamMiloapisComV1Alpha1ProtectedResource = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1ProtectedResourceData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1ProtectedResourceResponses,
    ReplaceIamMiloapisComV1Alpha1ProtectedResourceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/protectedresources/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified ProtectedResource
 */
export const readIamMiloapisComV1Alpha1ProtectedResourceStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1ProtectedResourceStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1ProtectedResourceStatusResponses,
    ReadIamMiloapisComV1Alpha1ProtectedResourceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/protectedresources/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified ProtectedResource
 */
export const patchIamMiloapisComV1Alpha1ProtectedResourceStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1ProtectedResourceStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1ProtectedResourceStatusResponses,
    PatchIamMiloapisComV1Alpha1ProtectedResourceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/protectedresources/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified ProtectedResource
 */
export const replaceIamMiloapisComV1Alpha1ProtectedResourceStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1ProtectedResourceStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1ProtectedResourceStatusResponses,
    ReplaceIamMiloapisComV1Alpha1ProtectedResourceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/protectedresources/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * list objects of kind Role
 */
export const listIamMiloapisComV1Alpha1RoleForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListIamMiloapisComV1Alpha1RoleForAllNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListIamMiloapisComV1Alpha1RoleForAllNamespacesResponses,
    ListIamMiloapisComV1Alpha1RoleForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/roles',
    ...options,
  });
};

/**
 * delete collection of UserDeactivation
 */
export const deleteIamMiloapisComV1Alpha1CollectionUserDeactivation = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteIamMiloapisComV1Alpha1CollectionUserDeactivationData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1CollectionUserDeactivationResponses,
    DeleteIamMiloapisComV1Alpha1CollectionUserDeactivationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userdeactivations',
    ...options,
  });
};

/**
 * list objects of kind UserDeactivation
 */
export const listIamMiloapisComV1Alpha1UserDeactivation = <ThrowOnError extends boolean = false>(
  options?: Options<ListIamMiloapisComV1Alpha1UserDeactivationData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListIamMiloapisComV1Alpha1UserDeactivationResponses,
    ListIamMiloapisComV1Alpha1UserDeactivationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userdeactivations',
    ...options,
  });
};

/**
 * create an UserDeactivation
 */
export const createIamMiloapisComV1Alpha1UserDeactivation = <ThrowOnError extends boolean = false>(
  options: Options<CreateIamMiloapisComV1Alpha1UserDeactivationData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateIamMiloapisComV1Alpha1UserDeactivationResponses,
    CreateIamMiloapisComV1Alpha1UserDeactivationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userdeactivations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete an UserDeactivation
 */
export const deleteIamMiloapisComV1Alpha1UserDeactivation = <ThrowOnError extends boolean = false>(
  options: Options<DeleteIamMiloapisComV1Alpha1UserDeactivationData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1UserDeactivationResponses,
    DeleteIamMiloapisComV1Alpha1UserDeactivationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userdeactivations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified UserDeactivation
 */
export const readIamMiloapisComV1Alpha1UserDeactivation = <ThrowOnError extends boolean = false>(
  options: Options<ReadIamMiloapisComV1Alpha1UserDeactivationData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1UserDeactivationResponses,
    ReadIamMiloapisComV1Alpha1UserDeactivationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userdeactivations/{name}',
    ...options,
  });
};

/**
 * partially update the specified UserDeactivation
 */
export const patchIamMiloapisComV1Alpha1UserDeactivation = <ThrowOnError extends boolean = false>(
  options: Options<PatchIamMiloapisComV1Alpha1UserDeactivationData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1UserDeactivationResponses,
    PatchIamMiloapisComV1Alpha1UserDeactivationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userdeactivations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified UserDeactivation
 */
export const replaceIamMiloapisComV1Alpha1UserDeactivation = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceIamMiloapisComV1Alpha1UserDeactivationData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1UserDeactivationResponses,
    ReplaceIamMiloapisComV1Alpha1UserDeactivationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userdeactivations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified UserDeactivation
 */
export const readIamMiloapisComV1Alpha1UserDeactivationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1UserDeactivationStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1UserDeactivationStatusResponses,
    ReadIamMiloapisComV1Alpha1UserDeactivationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userdeactivations/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified UserDeactivation
 */
export const patchIamMiloapisComV1Alpha1UserDeactivationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1UserDeactivationStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1UserDeactivationStatusResponses,
    PatchIamMiloapisComV1Alpha1UserDeactivationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userdeactivations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified UserDeactivation
 */
export const replaceIamMiloapisComV1Alpha1UserDeactivationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1UserDeactivationStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1UserDeactivationStatusResponses,
    ReplaceIamMiloapisComV1Alpha1UserDeactivationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userdeactivations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * list objects of kind UserInvitation
 */
export const listIamMiloapisComV1Alpha1UserInvitationForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListIamMiloapisComV1Alpha1UserInvitationForAllNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListIamMiloapisComV1Alpha1UserInvitationForAllNamespacesResponses,
    ListIamMiloapisComV1Alpha1UserInvitationForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userinvitations',
    ...options,
  });
};

/**
 * delete collection of UserPreference
 */
export const deleteIamMiloapisComV1Alpha1CollectionUserPreference = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteIamMiloapisComV1Alpha1CollectionUserPreferenceData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1CollectionUserPreferenceResponses,
    DeleteIamMiloapisComV1Alpha1CollectionUserPreferenceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userpreferences',
    ...options,
  });
};

/**
 * list objects of kind UserPreference
 */
export const listIamMiloapisComV1Alpha1UserPreference = <ThrowOnError extends boolean = false>(
  options?: Options<ListIamMiloapisComV1Alpha1UserPreferenceData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListIamMiloapisComV1Alpha1UserPreferenceResponses,
    ListIamMiloapisComV1Alpha1UserPreferenceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userpreferences',
    ...options,
  });
};

/**
 * create an UserPreference
 */
export const createIamMiloapisComV1Alpha1UserPreference = <ThrowOnError extends boolean = false>(
  options: Options<CreateIamMiloapisComV1Alpha1UserPreferenceData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateIamMiloapisComV1Alpha1UserPreferenceResponses,
    CreateIamMiloapisComV1Alpha1UserPreferenceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userpreferences',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete an UserPreference
 */
export const deleteIamMiloapisComV1Alpha1UserPreference = <ThrowOnError extends boolean = false>(
  options: Options<DeleteIamMiloapisComV1Alpha1UserPreferenceData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1UserPreferenceResponses,
    DeleteIamMiloapisComV1Alpha1UserPreferenceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userpreferences/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified UserPreference
 */
export const readIamMiloapisComV1Alpha1UserPreference = <ThrowOnError extends boolean = false>(
  options: Options<ReadIamMiloapisComV1Alpha1UserPreferenceData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1UserPreferenceResponses,
    ReadIamMiloapisComV1Alpha1UserPreferenceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userpreferences/{name}',
    ...options,
  });
};

/**
 * partially update the specified UserPreference
 */
export const patchIamMiloapisComV1Alpha1UserPreference = <ThrowOnError extends boolean = false>(
  options: Options<PatchIamMiloapisComV1Alpha1UserPreferenceData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1UserPreferenceResponses,
    PatchIamMiloapisComV1Alpha1UserPreferenceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userpreferences/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified UserPreference
 */
export const replaceIamMiloapisComV1Alpha1UserPreference = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceIamMiloapisComV1Alpha1UserPreferenceData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1UserPreferenceResponses,
    ReplaceIamMiloapisComV1Alpha1UserPreferenceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userpreferences/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified UserPreference
 */
export const readIamMiloapisComV1Alpha1UserPreferenceStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadIamMiloapisComV1Alpha1UserPreferenceStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1UserPreferenceStatusResponses,
    ReadIamMiloapisComV1Alpha1UserPreferenceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userpreferences/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified UserPreference
 */
export const patchIamMiloapisComV1Alpha1UserPreferenceStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchIamMiloapisComV1Alpha1UserPreferenceStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1UserPreferenceStatusResponses,
    PatchIamMiloapisComV1Alpha1UserPreferenceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userpreferences/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified UserPreference
 */
export const replaceIamMiloapisComV1Alpha1UserPreferenceStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceIamMiloapisComV1Alpha1UserPreferenceStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1UserPreferenceStatusResponses,
    ReplaceIamMiloapisComV1Alpha1UserPreferenceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/userpreferences/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of User
 */
export const deleteIamMiloapisComV1Alpha1CollectionUser = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteIamMiloapisComV1Alpha1CollectionUserData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1CollectionUserResponses,
    DeleteIamMiloapisComV1Alpha1CollectionUserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/users',
    ...options,
  });
};

/**
 * list objects of kind User
 */
export const listIamMiloapisComV1Alpha1User = <ThrowOnError extends boolean = false>(
  options?: Options<ListIamMiloapisComV1Alpha1UserData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListIamMiloapisComV1Alpha1UserResponses,
    ListIamMiloapisComV1Alpha1UserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/users',
    ...options,
  });
};

/**
 * create an User
 */
export const createIamMiloapisComV1Alpha1User = <ThrowOnError extends boolean = false>(
  options: Options<CreateIamMiloapisComV1Alpha1UserData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateIamMiloapisComV1Alpha1UserResponses,
    CreateIamMiloapisComV1Alpha1UserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete an User
 */
export const deleteIamMiloapisComV1Alpha1User = <ThrowOnError extends boolean = false>(
  options: Options<DeleteIamMiloapisComV1Alpha1UserData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteIamMiloapisComV1Alpha1UserResponses,
    DeleteIamMiloapisComV1Alpha1UserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/users/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified User
 */
export const readIamMiloapisComV1Alpha1User = <ThrowOnError extends boolean = false>(
  options: Options<ReadIamMiloapisComV1Alpha1UserData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1UserResponses,
    ReadIamMiloapisComV1Alpha1UserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/users/{name}',
    ...options,
  });
};

/**
 * partially update the specified User
 */
export const patchIamMiloapisComV1Alpha1User = <ThrowOnError extends boolean = false>(
  options: Options<PatchIamMiloapisComV1Alpha1UserData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1UserResponses,
    PatchIamMiloapisComV1Alpha1UserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/users/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified User
 */
export const replaceIamMiloapisComV1Alpha1User = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceIamMiloapisComV1Alpha1UserData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1UserResponses,
    ReplaceIamMiloapisComV1Alpha1UserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/users/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified User
 */
export const readIamMiloapisComV1Alpha1UserStatus = <ThrowOnError extends boolean = false>(
  options: Options<ReadIamMiloapisComV1Alpha1UserStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadIamMiloapisComV1Alpha1UserStatusResponses,
    ReadIamMiloapisComV1Alpha1UserStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/users/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified User
 */
export const patchIamMiloapisComV1Alpha1UserStatus = <ThrowOnError extends boolean = false>(
  options: Options<PatchIamMiloapisComV1Alpha1UserStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchIamMiloapisComV1Alpha1UserStatusResponses,
    PatchIamMiloapisComV1Alpha1UserStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/users/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified User
 */
export const replaceIamMiloapisComV1Alpha1UserStatus = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceIamMiloapisComV1Alpha1UserStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceIamMiloapisComV1Alpha1UserStatusResponses,
    ReplaceIamMiloapisComV1Alpha1UserStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/iam.miloapis.com/v1alpha1/users/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
