apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: cloud-portal
    app.kubernetes.io/name: cloud-portal
    app.kubernetes.io/version: 1.0.0
  name: cloud-portal
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: cloud-portal
    app.kubernetes.io/name: cloud-portal
  sessionAffinity: None
  type: ClusterIP
