version: '3.8'

services:
  grafana:
    image: grafana/grafana:11.6.0
    depends_on:
      - prometheus
    ports:
      - '3002:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dev/docker/grafana/:/etc/grafana/provisioning/
    env_file:
      - ./dev/docker/grafana/.env
  prometheus:
    image: prom/prometheus:v3.2.1
    ports:
      - '9090:9090'
    volumes:
      - ./dev/docker/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
volumes:
  prometheus-data: {}
  grafana-data: {}
