/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by @hey-api/openapi-ts

import type {
  DeleteResourcemanagerDatumapisComV1AlphaCollectionProjectResponse,
  ListResourcemanagerDatumapisComV1AlphaProjectResponse,
  CreateResourcemanagerDatumapisComV1AlphaProjectResponse,
  DeleteResourcemanagerDatumapisComV1AlphaProjectResponse,
  ReadResourcemanagerDatumapisComV1AlphaProjectResponse,
  PatchResourcemanagerDatumapisComV1AlphaProjectResponse,
  ReplaceResourcemanagerDatumapisComV1AlphaProjectResponse,
  ReadResourcemanagerDatumapisComV1AlphaProjectStatusResponse,
  PatchResourcemanagerDatumapisComV1AlphaProjectStatusResponse,
  ReplaceResourcemanagerDatumapisComV1AlphaProjectStatusResponse,
} from './types.gen'

const ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer = (data: any) => {
  if (data.remainingItemCount) {
    data.remainingItemCount = BigInt(data.remainingItemCount.toString())
  }
  return data
}

const ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(
      data.metadata,
    )
  }
  return data
}

export const deleteResourcemanagerDatumapisComV1AlphaCollectionProjectResponseTransformer =
  async (
    data: any,
  ): Promise<DeleteResourcemanagerDatumapisComV1AlphaCollectionProjectResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data)
    return data
  }

const ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer = (data: any) => {
  data = new Date(data)
  return data
}

const ioK8sApimachineryPkgApisMetaV1ManagedFieldsEntrySchemaResponseTransformer = (
  data: any,
) => {
  if (data.time) {
    data.time = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(data.time)
  }
  return data
}

const ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer = (data: any) => {
  if (data.creationTimestamp) {
    data.creationTimestamp = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(
      data.creationTimestamp,
    )
  }
  if (data.deletionGracePeriodSeconds) {
    data.deletionGracePeriodSeconds = BigInt(data.deletionGracePeriodSeconds.toString())
  }
  if (data.deletionTimestamp) {
    data.deletionTimestamp = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(
      data.deletionTimestamp,
    )
  }
  if (data.generation) {
    data.generation = BigInt(data.generation.toString())
  }
  if (data.managedFields) {
    data.managedFields = data.managedFields.map((item: any) => {
      return ioK8sApimachineryPkgApisMetaV1ManagedFieldsEntrySchemaResponseTransformer(
        item,
      )
    })
  }
  return data
}

const comDatumapisResourcemanagerV1AlphaProjectSchemaResponseTransformer = (
  data: any,
) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata,
    )
  }
  if (data.status) {
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime)
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString())
        }
        return item
      })
    }
    return data.status
  }
  return data
}

const comDatumapisResourcemanagerV1AlphaProjectListSchemaResponseTransformer = (
  data: any,
) => {
  data.items = data.items.map((item: any) => {
    return comDatumapisResourcemanagerV1AlphaProjectSchemaResponseTransformer(item)
  })
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(
      data.metadata,
    )
  }
  return data
}

export const listResourcemanagerDatumapisComV1AlphaProjectResponseTransformer = async (
  data: any,
): Promise<ListResourcemanagerDatumapisComV1AlphaProjectResponse> => {
  data = comDatumapisResourcemanagerV1AlphaProjectListSchemaResponseTransformer(data)
  return data
}

export const createResourcemanagerDatumapisComV1AlphaProjectResponseTransformer = async (
  data: any,
): Promise<CreateResourcemanagerDatumapisComV1AlphaProjectResponse> => {
  data = comDatumapisResourcemanagerV1AlphaProjectSchemaResponseTransformer(data)
  return data
}

export const deleteResourcemanagerDatumapisComV1AlphaProjectResponseTransformer = async (
  data: any,
): Promise<DeleteResourcemanagerDatumapisComV1AlphaProjectResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data)
  return data
}

export const readResourcemanagerDatumapisComV1AlphaProjectResponseTransformer = async (
  data: any,
): Promise<ReadResourcemanagerDatumapisComV1AlphaProjectResponse> => {
  data = comDatumapisResourcemanagerV1AlphaProjectSchemaResponseTransformer(data)
  return data
}

export const patchResourcemanagerDatumapisComV1AlphaProjectResponseTransformer = async (
  data: any,
): Promise<PatchResourcemanagerDatumapisComV1AlphaProjectResponse> => {
  data = comDatumapisResourcemanagerV1AlphaProjectSchemaResponseTransformer(data)
  return data
}

export const replaceResourcemanagerDatumapisComV1AlphaProjectResponseTransformer = async (
  data: any,
): Promise<ReplaceResourcemanagerDatumapisComV1AlphaProjectResponse> => {
  data = comDatumapisResourcemanagerV1AlphaProjectSchemaResponseTransformer(data)
  return data
}

export const readResourcemanagerDatumapisComV1AlphaProjectStatusResponseTransformer =
  async (
    data: any,
  ): Promise<ReadResourcemanagerDatumapisComV1AlphaProjectStatusResponse> => {
    data = comDatumapisResourcemanagerV1AlphaProjectSchemaResponseTransformer(data)
    return data
  }

export const patchResourcemanagerDatumapisComV1AlphaProjectStatusResponseTransformer =
  async (
    data: any,
  ): Promise<PatchResourcemanagerDatumapisComV1AlphaProjectStatusResponse> => {
    data = comDatumapisResourcemanagerV1AlphaProjectSchemaResponseTransformer(data)
    return data
  }

export const replaceResourcemanagerDatumapisComV1AlphaProjectStatusResponseTransformer =
  async (
    data: any,
  ): Promise<ReplaceResourcemanagerDatumapisComV1AlphaProjectStatusResponse> => {
    data = comDatumapisResourcemanagerV1AlphaProjectSchemaResponseTransformer(data)
    return data
  }
