// This file is auto-generated by @hey-api/openapi-ts
import type {
  CreateNetworkingDatumapisComV1AlphaNamespacedLocationResponse,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkResponse,
  CreateNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse,
  CreateNetworkingDatumapisComV1AlphaNamespacedSubnetResponse,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedLocationResponse,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkBindingResponse,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkContextResponse,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkPolicyResponse,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkResponse,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetClaimResponse,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetResponse,
  DeleteNetworkingDatumapisComV1AlphaNamespacedLocationResponse,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkResponse,
  DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse,
  DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetResponse,
  ListNetworkingDatumapisComV1AlphaLocationForAllNamespacesResponse,
  ListNetworkingDatumapisComV1AlphaNamespacedLocationResponse,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkResponse,
  ListNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse,
  ListNetworkingDatumapisComV1AlphaNamespacedSubnetResponse,
  ListNetworkingDatumapisComV1AlphaNetworkBindingForAllNamespacesResponse,
  ListNetworkingDatumapisComV1AlphaNetworkContextForAllNamespacesResponse,
  ListNetworkingDatumapisComV1AlphaNetworkForAllNamespacesResponse,
  ListNetworkingDatumapisComV1AlphaNetworkPolicyForAllNamespacesResponse,
  ListNetworkingDatumapisComV1AlphaSubnetClaimForAllNamespacesResponse,
  ListNetworkingDatumapisComV1AlphaSubnetForAllNamespacesResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedLocationResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetResponse,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedLocationResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetResponse,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetResponse,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponse,
} from './types.gen';

const ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer = (data: any) => {
  data = new Date(data);
  return data;
};

const ioK8sApimachineryPkgApisMetaV1ManagedFieldsEntrySchemaResponseTransformer = (data: any) => {
  if (data.time) {
    data.time = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(data.time);
  }
  return data;
};

const ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer = (data: any) => {
  if (data.creationTimestamp) {
    data.creationTimestamp = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(
      data.creationTimestamp
    );
  }
  if (data.deletionGracePeriodSeconds) {
    data.deletionGracePeriodSeconds = BigInt(data.deletionGracePeriodSeconds.toString());
  }
  if (data.deletionTimestamp) {
    data.deletionTimestamp = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(
      data.deletionTimestamp
    );
  }
  if (data.generation) {
    data.generation = BigInt(data.generation.toString());
  }
  if (data.managedFields) {
    data.managedFields = data.managedFields.map((item: any) => {
      return ioK8sApimachineryPkgApisMetaV1ManagedFieldsEntrySchemaResponseTransformer(item);
    });
  }
  return data;
};

const comDatumapisNetworkingV1AlphaLocationSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  if (data.status) {
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString());
        }
        return item;
      });
    }
    return data.status;
  }
  return data;
};

const ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer = (data: any) => {
  if (data.remainingItemCount) {
    data.remainingItemCount = BigInt(data.remainingItemCount.toString());
  }
  return data;
};

const comDatumapisNetworkingV1AlphaLocationListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comDatumapisNetworkingV1AlphaLocationSchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

export const listNetworkingDatumapisComV1AlphaLocationForAllNamespacesResponseTransformer = async (
  data: any
): Promise<ListNetworkingDatumapisComV1AlphaLocationForAllNamespacesResponse> => {
  data = comDatumapisNetworkingV1AlphaLocationListSchemaResponseTransformer(data);
  return data;
};

const ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedLocationResponseTransformer =
  async (
    data: any
  ): Promise<DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedLocationResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

export const listNetworkingDatumapisComV1AlphaNamespacedLocationResponseTransformer = async (
  data: any
): Promise<ListNetworkingDatumapisComV1AlphaNamespacedLocationResponse> => {
  data = comDatumapisNetworkingV1AlphaLocationListSchemaResponseTransformer(data);
  return data;
};

export const createNetworkingDatumapisComV1AlphaNamespacedLocationResponseTransformer = async (
  data: any
): Promise<CreateNetworkingDatumapisComV1AlphaNamespacedLocationResponse> => {
  data = comDatumapisNetworkingV1AlphaLocationSchemaResponseTransformer(data);
  return data;
};

export const deleteNetworkingDatumapisComV1AlphaNamespacedLocationResponseTransformer = async (
  data: any
): Promise<DeleteNetworkingDatumapisComV1AlphaNamespacedLocationResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
  return data;
};

export const readNetworkingDatumapisComV1AlphaNamespacedLocationResponseTransformer = async (
  data: any
): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedLocationResponse> => {
  data = comDatumapisNetworkingV1AlphaLocationSchemaResponseTransformer(data);
  return data;
};

export const patchNetworkingDatumapisComV1AlphaNamespacedLocationResponseTransformer = async (
  data: any
): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedLocationResponse> => {
  data = comDatumapisNetworkingV1AlphaLocationSchemaResponseTransformer(data);
  return data;
};

export const replaceNetworkingDatumapisComV1AlphaNamespacedLocationResponseTransformer = async (
  data: any
): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationResponse> => {
  data = comDatumapisNetworkingV1AlphaLocationSchemaResponseTransformer(data);
  return data;
};

export const readNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponseTransformer = async (
  data: any
): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponse> => {
  data = comDatumapisNetworkingV1AlphaLocationSchemaResponseTransformer(data);
  return data;
};

export const patchNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponseTransformer = async (
  data: any
): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponse> => {
  data = comDatumapisNetworkingV1AlphaLocationSchemaResponseTransformer(data);
  return data;
};

export const replaceNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaLocationSchemaResponseTransformer(data);
    return data;
  };

export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkBindingResponseTransformer =
  async (
    data: any
  ): Promise<DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkBindingResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

const comDatumapisNetworkingV1AlphaNetworkBindingSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  if (data.status) {
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString());
        }
        return item;
      });
    }
    return data.status;
  }
  return data;
};

const comDatumapisNetworkingV1AlphaNetworkBindingListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comDatumapisNetworkingV1AlphaNetworkBindingSchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

export const listNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponseTransformer = async (
  data: any
): Promise<ListNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkBindingListSchemaResponseTransformer(data);
  return data;
};

export const createNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponseTransformer =
  async (
    data: any
  ): Promise<CreateNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkBindingSchemaResponseTransformer(data);
    return data;
  };

export const deleteNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponseTransformer =
  async (
    data: any
  ): Promise<DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

export const readNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponseTransformer = async (
  data: any
): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkBindingSchemaResponseTransformer(data);
  return data;
};

export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponseTransformer = async (
  data: any
): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkBindingSchemaResponseTransformer(data);
  return data;
};

export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkBindingSchemaResponseTransformer(data);
    return data;
  };

export const readNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkBindingSchemaResponseTransformer(data);
    return data;
  };

export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponseTransformer =
  async (
    data: any
  ): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkBindingSchemaResponseTransformer(data);
    return data;
  };

export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkBindingSchemaResponseTransformer(data);
    return data;
  };

export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkContextResponseTransformer =
  async (
    data: any
  ): Promise<DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkContextResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

const comDatumapisNetworkingV1AlphaNetworkContextSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  if (data.status) {
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString());
        }
        return item;
      });
    }
    return data.status;
  }
  return data;
};

const comDatumapisNetworkingV1AlphaNetworkContextListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comDatumapisNetworkingV1AlphaNetworkContextSchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

export const listNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponseTransformer = async (
  data: any
): Promise<ListNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkContextListSchemaResponseTransformer(data);
  return data;
};

export const createNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponseTransformer =
  async (
    data: any
  ): Promise<CreateNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkContextSchemaResponseTransformer(data);
    return data;
  };

export const deleteNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponseTransformer =
  async (
    data: any
  ): Promise<DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

export const readNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponseTransformer = async (
  data: any
): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkContextSchemaResponseTransformer(data);
  return data;
};

export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponseTransformer = async (
  data: any
): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkContextSchemaResponseTransformer(data);
  return data;
};

export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkContextSchemaResponseTransformer(data);
    return data;
  };

export const readNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkContextSchemaResponseTransformer(data);
    return data;
  };

export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponseTransformer =
  async (
    data: any
  ): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkContextSchemaResponseTransformer(data);
    return data;
  };

export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkContextSchemaResponseTransformer(data);
    return data;
  };

export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkPolicyResponseTransformer =
  async (
    data: any
  ): Promise<DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkPolicyResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

const comDatumapisNetworkingV1AlphaNetworkPolicySchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  return data;
};

const comDatumapisNetworkingV1AlphaNetworkPolicyListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comDatumapisNetworkingV1AlphaNetworkPolicySchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

export const listNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponseTransformer = async (
  data: any
): Promise<ListNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkPolicyListSchemaResponseTransformer(data);
  return data;
};

export const createNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponseTransformer = async (
  data: any
): Promise<CreateNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkPolicySchemaResponseTransformer(data);
  return data;
};

export const deleteNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponseTransformer = async (
  data: any
): Promise<DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
  return data;
};

export const readNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponseTransformer = async (
  data: any
): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkPolicySchemaResponseTransformer(data);
  return data;
};

export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponseTransformer = async (
  data: any
): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkPolicySchemaResponseTransformer(data);
  return data;
};

export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkPolicySchemaResponseTransformer(data);
    return data;
  };

export const readNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkPolicySchemaResponseTransformer(data);
    return data;
  };

export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponseTransformer =
  async (
    data: any
  ): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkPolicySchemaResponseTransformer(data);
    return data;
  };

export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkPolicySchemaResponseTransformer(data);
    return data;
  };

export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkResponseTransformer =
  async (
    data: any
  ): Promise<DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

const comDatumapisNetworkingV1AlphaNetworkSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  if (data.status) {
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString());
        }
        return item;
      });
    }
    return data.status;
  }
  return data;
};

const comDatumapisNetworkingV1AlphaNetworkListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comDatumapisNetworkingV1AlphaNetworkSchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

export const listNetworkingDatumapisComV1AlphaNamespacedNetworkResponseTransformer = async (
  data: any
): Promise<ListNetworkingDatumapisComV1AlphaNamespacedNetworkResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkListSchemaResponseTransformer(data);
  return data;
};

export const createNetworkingDatumapisComV1AlphaNamespacedNetworkResponseTransformer = async (
  data: any
): Promise<CreateNetworkingDatumapisComV1AlphaNamespacedNetworkResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkSchemaResponseTransformer(data);
  return data;
};

export const deleteNetworkingDatumapisComV1AlphaNamespacedNetworkResponseTransformer = async (
  data: any
): Promise<DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
  return data;
};

export const readNetworkingDatumapisComV1AlphaNamespacedNetworkResponseTransformer = async (
  data: any
): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkSchemaResponseTransformer(data);
  return data;
};

export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkResponseTransformer = async (
  data: any
): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkSchemaResponseTransformer(data);
  return data;
};

export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkResponseTransformer = async (
  data: any
): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkSchemaResponseTransformer(data);
  return data;
};

export const readNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponseTransformer = async (
  data: any
): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkSchemaResponseTransformer(data);
  return data;
};

export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponseTransformer = async (
  data: any
): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkSchemaResponseTransformer(data);
  return data;
};

export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkSchemaResponseTransformer(data);
    return data;
  };

export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetClaimResponseTransformer =
  async (
    data: any
  ): Promise<DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetClaimResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

const comDatumapisNetworkingV1AlphaSubnetClaimSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  if (data.status) {
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString());
        }
        return item;
      });
    }
    return data.status;
  }
  return data;
};

const comDatumapisNetworkingV1AlphaSubnetClaimListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comDatumapisNetworkingV1AlphaSubnetClaimSchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

export const listNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponseTransformer = async (
  data: any
): Promise<ListNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetClaimListSchemaResponseTransformer(data);
  return data;
};

export const createNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponseTransformer = async (
  data: any
): Promise<CreateNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetClaimSchemaResponseTransformer(data);
  return data;
};

export const deleteNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponseTransformer = async (
  data: any
): Promise<DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
  return data;
};

export const readNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponseTransformer = async (
  data: any
): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetClaimSchemaResponseTransformer(data);
  return data;
};

export const patchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponseTransformer = async (
  data: any
): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetClaimSchemaResponseTransformer(data);
  return data;
};

export const replaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponseTransformer = async (
  data: any
): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetClaimSchemaResponseTransformer(data);
  return data;
};

export const readNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaSubnetClaimSchemaResponseTransformer(data);
    return data;
  };

export const patchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponseTransformer =
  async (
    data: any
  ): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaSubnetClaimSchemaResponseTransformer(data);
    return data;
  };

export const replaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponse> => {
    data = comDatumapisNetworkingV1AlphaSubnetClaimSchemaResponseTransformer(data);
    return data;
  };

export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetResponseTransformer =
  async (
    data: any
  ): Promise<DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

const comDatumapisNetworkingV1AlphaSubnetSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  if (data.status) {
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString());
        }
        return item;
      });
    }
    return data.status;
  }
  return data;
};

const comDatumapisNetworkingV1AlphaSubnetListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comDatumapisNetworkingV1AlphaSubnetSchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

export const listNetworkingDatumapisComV1AlphaNamespacedSubnetResponseTransformer = async (
  data: any
): Promise<ListNetworkingDatumapisComV1AlphaNamespacedSubnetResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetListSchemaResponseTransformer(data);
  return data;
};

export const createNetworkingDatumapisComV1AlphaNamespacedSubnetResponseTransformer = async (
  data: any
): Promise<CreateNetworkingDatumapisComV1AlphaNamespacedSubnetResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetSchemaResponseTransformer(data);
  return data;
};

export const deleteNetworkingDatumapisComV1AlphaNamespacedSubnetResponseTransformer = async (
  data: any
): Promise<DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
  return data;
};

export const readNetworkingDatumapisComV1AlphaNamespacedSubnetResponseTransformer = async (
  data: any
): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedSubnetResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetSchemaResponseTransformer(data);
  return data;
};

export const patchNetworkingDatumapisComV1AlphaNamespacedSubnetResponseTransformer = async (
  data: any
): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedSubnetResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetSchemaResponseTransformer(data);
  return data;
};

export const replaceNetworkingDatumapisComV1AlphaNamespacedSubnetResponseTransformer = async (
  data: any
): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetSchemaResponseTransformer(data);
  return data;
};

export const readNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponseTransformer = async (
  data: any
): Promise<ReadNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetSchemaResponseTransformer(data);
  return data;
};

export const patchNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponseTransformer = async (
  data: any
): Promise<PatchNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetSchemaResponseTransformer(data);
  return data;
};

export const replaceNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponseTransformer = async (
  data: any
): Promise<ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetSchemaResponseTransformer(data);
  return data;
};

export const listNetworkingDatumapisComV1AlphaNetworkBindingForAllNamespacesResponseTransformer =
  async (
    data: any
  ): Promise<ListNetworkingDatumapisComV1AlphaNetworkBindingForAllNamespacesResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkBindingListSchemaResponseTransformer(data);
    return data;
  };

export const listNetworkingDatumapisComV1AlphaNetworkContextForAllNamespacesResponseTransformer =
  async (
    data: any
  ): Promise<ListNetworkingDatumapisComV1AlphaNetworkContextForAllNamespacesResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkContextListSchemaResponseTransformer(data);
    return data;
  };

export const listNetworkingDatumapisComV1AlphaNetworkPolicyForAllNamespacesResponseTransformer =
  async (
    data: any
  ): Promise<ListNetworkingDatumapisComV1AlphaNetworkPolicyForAllNamespacesResponse> => {
    data = comDatumapisNetworkingV1AlphaNetworkPolicyListSchemaResponseTransformer(data);
    return data;
  };

export const listNetworkingDatumapisComV1AlphaNetworkForAllNamespacesResponseTransformer = async (
  data: any
): Promise<ListNetworkingDatumapisComV1AlphaNetworkForAllNamespacesResponse> => {
  data = comDatumapisNetworkingV1AlphaNetworkListSchemaResponseTransformer(data);
  return data;
};

export const listNetworkingDatumapisComV1AlphaSubnetClaimForAllNamespacesResponseTransformer =
  async (
    data: any
  ): Promise<ListNetworkingDatumapisComV1AlphaSubnetClaimForAllNamespacesResponse> => {
    data = comDatumapisNetworkingV1AlphaSubnetClaimListSchemaResponseTransformer(data);
    return data;
  };

export const listNetworkingDatumapisComV1AlphaSubnetForAllNamespacesResponseTransformer = async (
  data: any
): Promise<ListNetworkingDatumapisComV1AlphaSubnetForAllNamespacesResponse> => {
  data = comDatumapisNetworkingV1AlphaSubnetListSchemaResponseTransformer(data);
  return data;
};
