#!/usr/bin/env bun
/**
 * Generate iOS splash screens and PWA icons.
 *
 * Usage: bun run pwa:assets
 *
 * Splash screens use pwa-asset-generator (headless Chrome). Install it
 * only while regenerating (`bun add -d pwa-asset-generator`) so it does
 * not hoist unrelated lockfile versions. Icons are rasterized with the
 * same Chrome binary so 192/512/1024 and maskable sizes stay aligned
 * with the canyon-clay mark.
 *
 * Source is `public/images/logo-mark.svg` (canyon clay `#BF9595`). The
 * wordmark in `logo.svg` is navy and disappears on the dark splash.
 */
import { PWA_THEME_COLOR_DARK, PWA_THEME_COLOR_LIGHT } from '../app/features/pwa/theme';
import { execFile } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

const ROOT = join(import.meta.dirname, '..');
const LOGO_MARK = join(ROOT, 'public/images/logo-mark.svg');
const SPLASH_LIGHT_DIR = join(ROOT, 'public/splash/light');
const SPLASH_DARK_DIR = join(ROOT, 'public/splash/dark');
const FAVICONS_DIR = join(ROOT, 'public/favicons');
const DATA_FILE = join(ROOT, 'app/components/misc/pwa-splash-links.data.ts');

const LIGHT_BG = PWA_THEME_COLOR_LIGHT;
const DARK_BG = PWA_THEME_COLOR_DARK;

const CHROME_CANDIDATES = [
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/Applications/Chromium.app/Contents/MacOS/Chromium',
  '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
  '/usr/bin/google-chrome',
  '/usr/bin/google-chrome-stable',
  '/usr/bin/chromium',
  '/usr/bin/chromium-browser',
];

type SplashLink = { href: string; media: string };

function parseStartupImageLinks(html: string): SplashLink[] {
  const links: SplashLink[] = [];
  for (const tag of html.match(/<link\b[^>]*>/gi) ?? []) {
    const href = tag.match(/\bhref=["']([^"']+)["']/)?.[1];
    const media = tag.match(/\bmedia=["']([^"']+)["']/)?.[1];
    if (href && media) links.push({ href, media });
  }
  return links;
}

function withColorScheme(media: string, scheme: 'light' | 'dark'): string {
  if (media.includes('prefers-color-scheme')) return media;
  return `${media} and (prefers-color-scheme: ${scheme})`;
}

function findChrome(): string {
  for (const candidate of CHROME_CANDIDATES) {
    if (existsSync(candidate)) return candidate;
  }
  throw new Error(
    'Chrome/Chromium not found. Install Chrome to generate PWA splash screens and icons.'
  );
}

async function rasterizePng(opts: {
  size: number;
  background: string;
  paddingRatio: number;
  outPath: string;
}) {
  const chrome = findChrome();
  const svg = await readFile(LOGO_MARK, 'utf8');
  const inner = Math.round(opts.size * (1 - opts.paddingRatio * 2));
  const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    html, body {
      margin: 0;
      width: ${opts.size}px;
      height: ${opts.size}px;
      background: ${opts.background};
    }
    body {
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .mark {
      width: ${inner}px;
      height: ${inner}px;
      display: flex;
    }
    .mark svg {
      width: 100%;
      height: 100%;
    }
  </style>
</head>
<body>
  <div class="mark">${svg}</div>
</body>
</html>`;

  const workDir = join(tmpdir(), `datum-pwa-${opts.size}-${Date.now()}`);
  await mkdir(workDir, { recursive: true });
  const htmlPath = join(workDir, 'icon.html');
  await writeFile(htmlPath, html);

  try {
    await execFileAsync(chrome, [
      '--headless=new',
      '--disable-gpu',
      '--hide-scrollbars',
      '--allow-file-access-from-files',
      `--window-size=${opts.size},${opts.size}`,
      `--screenshot=${opts.outPath}`,
      pathToFileURL(htmlPath).href,
    ]);
  } finally {
    await rm(workDir, { recursive: true, force: true });
  }
}

function serializeDataFile(links: SplashLink[]): string {
  const body = links
    .map(
      (link) =>
        `  {\n    href: '${link.href}',\n    media: '${link.media.replace(/'/g, "\\'")}',\n  }`
    )
    .join(',\n');

  return `export type PwaSplashLink = {
  href: string;
  media: string;
};

/** Generated by \`bun run pwa:assets\`. Do not edit by hand. */
export const PWA_SPLASH_LINKS: PwaSplashLink[] = [
${body}
];
`;
}

async function main() {
  if (!existsSync(LOGO_MARK)) {
    throw new Error(`Missing ${LOGO_MARK}`);
  }

  findChrome();

  let generateImages: (typeof import('pwa-asset-generator'))['generateImages'];
  try {
    ({ generateImages } = await import('pwa-asset-generator'));
  } catch {
    throw new Error(
      'pwa-asset-generator is not installed. Run `bun add -d pwa-asset-generator`, regenerate, then remove the dependency.'
    );
  }

  await mkdir(SPLASH_LIGHT_DIR, { recursive: true });
  await mkdir(SPLASH_DARK_DIR, { recursive: true });
  await mkdir(FAVICONS_DIR, { recursive: true });

  console.info('Generating light iOS splash screens…');
  const light = await generateImages(LOGO_MARK, SPLASH_LIGHT_DIR, {
    scrape: false,
    background: LIGHT_BG,
    splashOnly: true,
    favicon: false,
    mstile: false,
    type: 'png',
    padding: '8%',
    darkMode: false,
    pathOverride: '/splash/light',
    log: true,
  });

  console.info('Generating dark iOS splash screens…');
  const dark = await generateImages(LOGO_MARK, SPLASH_DARK_DIR, {
    scrape: false,
    background: DARK_BG,
    splashOnly: true,
    favicon: false,
    mstile: false,
    type: 'png',
    padding: '8%',
    darkMode: true,
    pathOverride: '/splash/dark',
    log: true,
  });

  console.info('Generating app icons…');
  await rasterizePng({
    size: 192,
    background: LIGHT_BG,
    paddingRatio: 0.12,
    outPath: join(FAVICONS_DIR, 'icon-192.png'),
  });
  await rasterizePng({
    size: 512,
    background: LIGHT_BG,
    paddingRatio: 0.12,
    outPath: join(FAVICONS_DIR, 'icon-512.png'),
  });
  await rasterizePng({
    size: 1024,
    background: LIGHT_BG,
    paddingRatio: 0.12,
    outPath: join(FAVICONS_DIR, 'icon-1024.png'),
  });
  await rasterizePng({
    size: 192,
    background: LIGHT_BG,
    paddingRatio: 0.2,
    outPath: join(FAVICONS_DIR, 'maskable-192.png'),
  });
  await rasterizePng({
    size: 512,
    background: LIGHT_BG,
    paddingRatio: 0.2,
    outPath: join(FAVICONS_DIR, 'maskable-512.png'),
  });

  const lightLinks = parseStartupImageLinks(light.htmlMeta.appleLaunchImage ?? '').map((link) => ({
    ...link,
    media: withColorScheme(link.media, 'light'),
  }));
  const darkLinks = parseStartupImageLinks(
    dark.htmlMeta.appleLaunchImageDarkMode ?? dark.htmlMeta.appleLaunchImage ?? ''
  ).map((link) => ({ ...link, media: withColorScheme(link.media, 'dark') }));

  const links = [...lightLinks, ...darkLinks];

  if (!links.length) {
    throw new Error('pwa-asset-generator returned no apple-touch-startup-image tags');
  }

  await writeFile(DATA_FILE, serializeDataFile(links));
  console.info(`Wrote ${links.length} splash links → ${DATA_FILE}`);
  console.info('Done.');
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
