// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from '../shared/client';
import { client } from '../shared/client.gen';
import type {
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingData,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountData,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesData,
  ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesErrors,
  ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesResponses,
  ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesData,
  ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesErrors,
  ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesResponses,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * list objects of kind BillingAccountBinding
 */
export const listBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesResponses,
    ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/billing.miloapis.com/v1alpha1/billingaccountbindings', ...options });

/**
 * list objects of kind BillingAccount
 */
export const listBillingMiloapisComV1Alpha1BillingAccountForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesResponses,
    ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/billing.miloapis.com/v1alpha1/billingaccounts', ...options });

/**
 * delete collection of BillingAccountBinding
 */
export const deleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings',
    ...options,
  });

/**
 * list objects of kind BillingAccountBinding
 */
export const listBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings',
    ...options,
  });

/**
 * create a BillingAccountBinding
 */
export const createBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a BillingAccountBinding
 */
export const deleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified BillingAccountBinding
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
  });

/**
 * partially update the specified BillingAccountBinding
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified BillingAccountBinding
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified BillingAccountBinding
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified BillingAccountBinding
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified BillingAccountBinding
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of BillingAccount
 */
export const deleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts',
    ...options,
  });

/**
 * list objects of kind BillingAccount
 */
export const listBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts',
    ...options,
  });

/**
 * create a BillingAccount
 */
export const createBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a BillingAccount
 */
export const deleteBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified BillingAccount
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
  });

/**
 * partially update the specified BillingAccount
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified BillingAccount
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified BillingAccount
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccountStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified BillingAccount
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified BillingAccount
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
    ThrowOnError
  >({
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
