import type { SSEStreamingApi } from 'hono/streaming';
import { z } from 'zod';

// ─── Client Management ───────────────────────────────

/**
 * A connected browser client with an open SSE stream.
 * Created when `GET /api/watch/stream` is called; removed on disconnect.
 */
export interface WatchClient {
  /** Unique client ID (UUID generated by the browser's WatchManager). */
  id: string;
  /** User ID from session (`session.sub`) for ownership validation. */
  userId: string;
  /** Hono SSE stream writer used to push events to the browser. */
  stream: SSEStreamingApi;
  /** Set of watch keys this client is subscribed to. */
  subscriptions: Set<string>;
  /** OAuth access token for upstream K8s API auth (refreshed on each subscribe). */
  token: string;
  /** Timestamp of last successful SSE write to this client. */
  lastActivity: number;
}

// ─── Upstream Connection ─────────────────────────────

/**
 * A persistent upstream connection to the K8s Watch API.
 * Shared across all browser clients watching the same resource.
 */
export interface UpstreamWatch {
  /** Deterministic watch key matching the channel name sent to clients. */
  key: string;
  /** Base upstream URL (without resourceVersion query param). */
  url: string;
  /** AbortController for the current fetch — replaced on reconnection. */
  controller: AbortController;
  /** Latest resourceVersion received; used to resume after reconnection. */
  resourceVersion: string;
  /** Timestamp of the last data chunk received from K8s. */
  lastActivity: number;
  /** Number of consecutive reconnection attempts (reset on successful connect). */
  reconnectAttempts: number;
  /** True while the initial fetch is in-flight. */
  isConnecting: boolean;
  /** User ID of the client that created this upstream (for token affinity on reconnection). */
  creatorUserId: string;
}

/**
 * A watch channel: the set of clients an upstream fans out to, plus the
 * record of who has been shown to be entitled to it.
 *
 * Created and destroyed with its {@link UpstreamWatch} — see
 * `WatchHub.closeChannel`. The two lifetimes have to match: a subscriber set
 * that outlives its upstream is a set of clients the *next* upstream, opened
 * and authorized by somebody else, would fan out to.
 */
export interface WatchChannel {
  /** Channel key — the name clients subscribe and unsubscribe by. */
  key: string;
  /** Upstream URL this channel is served by. Fixed for the channel's life. */
  url: string;
  /** Client IDs currently subscribed. This is the fan-out set. */
  subscribers: Set<string>;
  /**
   * User ID → epoch ms after which that user must be re-checked against
   * {@link url} before being (re-)admitted.
   *
   * A memo, not a grant: it exists so navigation churn does not pay for a
   * round trip on every re-subscribe. Bounded so that a revoked user is not
   * admitted indefinitely on the strength of a check made once.
   */
  authorizedUntil: Map<string, number>;
}

/**
 * Outcome of {@link WatchHub.registerClient}. A rejected registration has to
 * say why: "at capacity" is a server-load condition, while "client id in use"
 * means the id is already bound to a different user and rebinding it would
 * hand over that id's channel memberships.
 */
export type RegisterClientResult = 'accepted' | 'at-capacity' | 'client-id-in-use';

// ─── Subscribe/Unsubscribe ───────────────────────────

/** Body of `POST /api/watch/subscribe`. */
export interface WatchSubscribeRequest {
  clientId: string;
  /** K8s resource type path, e.g. `'apis/networking.datumapis.com/v1alpha/domains'`. */
  resourceType: string;
  /** Organization ID (for org-scoped resources like projects). */
  orgId?: string;
  /** Project ID (for project-scoped resources). */
  projectId?: string;
  /** K8s namespace (usually `'default'` for project resources). */
  namespace?: string;
  /** Resource name for single-resource watches (uses fieldSelector). */
  name?: string;
  /** K8s label selector (e.g. `'app=web'`). */
  labelSelector?: string;
  /** K8s field selector (e.g. `'status.phase=Running'`). */
  fieldSelector?: string;
  /** If true, watches user-scoped resources using the session-authenticated user's identity. */
  userScoped?: boolean;
}

/** Body of `POST /api/watch/unsubscribe`. */
export interface WatchUnsubscribeRequest {
  clientId: string;
  /** The watch key / channel name returned by subscribe. */
  channel: string;
}

// ─── SSE Events ──────────────────────────────────────

/**
 * Discriminated union of all SSE events the WatchHub can send to a client.
 *
 * - `connected` — sent immediately after SSE stream opens. Carries the session
 *   user id, which the browser needs to derive user-scoped channel keys the
 *   same way the hub does.
 * - `subscribed` / `unsubscribed` — confirmations for subscribe/unsubscribe requests.
 * - `watch` — a K8s watch event (ADDED / MODIFIED / DELETED) with the full object.
 * - `watch-error` — a non-410 error from the upstream K8s watch stream.
 * - `resync` — the upstream reset to `resourceVersion: '0'` after a 410
 *   Gone — see WatchEventType.RESYNC. Unlike `subscribed`, broadcast to
 *   every subscriber of the channel, because the reset is upstream-wide and
 *   no client asked for it.
 * - `heartbeat` — periodic keep-alive to prevent proxy/LB timeouts.
 */
export type WatchSSEEvent =
  | { event: 'connected'; data: { clientId: string; userId: string } }
  | { event: 'subscribed'; data: { channel: string } }
  | { event: 'unsubscribed'; data: { channel: string } }
  | {
      event: 'watch';
      data: { channel: string; type: string; object: unknown; resourceVersion?: string };
    }
  | {
      event: 'watch-error';
      data: { channel: string; code?: number; reason?: string; message?: string };
    }
  | { event: 'resync'; data: { channel: string } }
  | { event: 'heartbeat'; data: { ts: number } };

// ─── Stats ───────────────────────────────────────────

/** Return type for the debug `/api/watch/stats` endpoint. */
export interface WatchStats {
  clients: number;
  upstreams: number;
  subscriptions: Record<string, number>;
}

// ─── Validation Schemas ──────────────────────────────

/**
 * Validates K8s API path format without hardcoding specific resource types.
 * Accepts:
 *   - `apis/<group>/<version>/<resource>`  (CRDs, e.g. `apis/networking.datumapis.com/v1alpha/domains`)
 *   - `api/<version>/<resource>`           (core, e.g. `api/v1/secrets`)
 * Rejects path traversal (`..`), double slashes, and non-K8s paths.
 */
const K8S_RESOURCE_TYPE =
  /^api(?:s\/[a-z][a-z0-9.-]*(?:\/[a-z][a-z0-9.-]*)*)?\/v[a-z0-9]+[a-z0-9]*\/[a-z][a-z0-9-]*$/;

/**
 * K8s-style identifiers: lowercase alphanumeric + hyphens + dots, 1–63 chars.
 *
 * Note for anyone widening these patterns: channel keys are these fields
 * joined with ':' (see `buildWatchChannelKey`), and that join is only
 * unambiguous because none of the patterns below — nor
 * {@link K8S_RESOURCE_TYPE} or {@link SELECTOR_PATTERN} — admits a ':'.
 * Allowing one would let two different subscriptions produce the same key.
 */
const K8S_IDENTIFIER = /^[a-z0-9]([a-z0-9.-]{0,61}[a-z0-9])?$/;

/** Basic label/field selector chars: alphanumeric, dots, equals, commas, etc. */
const SELECTOR_PATTERN = /^[a-zA-Z0-9_.=!,/()-]+$/;

/** Runtime validation schema for `POST /api/watch/subscribe` request bodies. */
export const watchSubscribeSchema = z.object({
  clientId: z.string().uuid(),
  resourceType: z
    .string()
    .min(1)
    .max(256)
    .regex(K8S_RESOURCE_TYPE, 'Invalid K8s resource type path'),
  orgId: z.string().regex(K8S_IDENTIFIER).optional(),
  projectId: z.string().regex(K8S_IDENTIFIER).optional(),
  namespace: z.string().regex(K8S_IDENTIFIER).optional(),
  name: z.string().regex(K8S_IDENTIFIER).optional(),
  labelSelector: z.string().regex(SELECTOR_PATTERN).max(512).optional(),
  fieldSelector: z.string().regex(SELECTOR_PATTERN).max(512).optional(),
  userScoped: z.boolean().optional(),
});

/** Runtime validation schema for `POST /api/watch/unsubscribe` request bodies. */
export const watchUnsubscribeSchema = z.object({
  clientId: z.string().uuid(),
  channel: z.string().min(1).max(1024),
});
