name: Set Project Month

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  set-month:
    uses: datum-cloud/actions/.github/workflows/set-project-month.yaml@545f34cd6f35e9688c9a04a7e890281bcdbaefd2 # v1.14.0
    secrets: inherit
