name: Set Project Month

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  set-month:
    uses: datum-cloud/actions/.github/workflows/set-project-month.yaml@ae21ec822981e1ab9e48023ac3da57c964edad04 # v1.18.0
    secrets: inherit
