name: Set Project Month

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  set-month:
    uses: datum-cloud/actions/.github/workflows/set-project-month.yaml@f8f2a7df9e691c6eec21ffb22c554c7e9a0bf9d9 # v1.15.0
    secrets: inherit
