name: Typecheck

on:
  pull_request:
  push:
    # https://github.com/actions/runner/issues/2324
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches: ['main']

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    needs: check-files
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Typecheck
        run: bun typecheck
