// This file is auto-generated by @hey-api/openapi-ts
import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from '../shared/client';
import { client } from '../shared/client.gen';
import type {
  CreateLocationsMiloapisComV1Alpha1LocationClassData,
  CreateLocationsMiloapisComV1Alpha1LocationClassErrors,
  CreateLocationsMiloapisComV1Alpha1LocationClassResponses,
  CreateLocationsMiloapisComV1Alpha1LocationData,
  CreateLocationsMiloapisComV1Alpha1LocationErrors,
  CreateLocationsMiloapisComV1Alpha1LocationResponses,
  CreateLocationsMiloapisComV1Alpha1ServingLocationData,
  CreateLocationsMiloapisComV1Alpha1ServingLocationErrors,
  CreateLocationsMiloapisComV1Alpha1ServingLocationResponses,
  DeleteLocationsMiloapisComV1Alpha1CollectionLocationClassData,
  DeleteLocationsMiloapisComV1Alpha1CollectionLocationClassErrors,
  DeleteLocationsMiloapisComV1Alpha1CollectionLocationClassResponses,
  DeleteLocationsMiloapisComV1Alpha1CollectionLocationData,
  DeleteLocationsMiloapisComV1Alpha1CollectionLocationErrors,
  DeleteLocationsMiloapisComV1Alpha1CollectionLocationResponses,
  DeleteLocationsMiloapisComV1Alpha1CollectionServingLocationData,
  DeleteLocationsMiloapisComV1Alpha1CollectionServingLocationErrors,
  DeleteLocationsMiloapisComV1Alpha1CollectionServingLocationResponses,
  DeleteLocationsMiloapisComV1Alpha1LocationClassData,
  DeleteLocationsMiloapisComV1Alpha1LocationClassErrors,
  DeleteLocationsMiloapisComV1Alpha1LocationClassResponses,
  DeleteLocationsMiloapisComV1Alpha1LocationData,
  DeleteLocationsMiloapisComV1Alpha1LocationErrors,
  DeleteLocationsMiloapisComV1Alpha1LocationResponses,
  DeleteLocationsMiloapisComV1Alpha1ServingLocationData,
  DeleteLocationsMiloapisComV1Alpha1ServingLocationErrors,
  DeleteLocationsMiloapisComV1Alpha1ServingLocationResponses,
  ListLocationsMiloapisComV1Alpha1LocationClassData,
  ListLocationsMiloapisComV1Alpha1LocationClassErrors,
  ListLocationsMiloapisComV1Alpha1LocationClassResponses,
  ListLocationsMiloapisComV1Alpha1LocationData,
  ListLocationsMiloapisComV1Alpha1LocationErrors,
  ListLocationsMiloapisComV1Alpha1LocationResponses,
  ListLocationsMiloapisComV1Alpha1ServingLocationData,
  ListLocationsMiloapisComV1Alpha1ServingLocationErrors,
  ListLocationsMiloapisComV1Alpha1ServingLocationResponses,
  PatchLocationsMiloapisComV1Alpha1LocationClassData,
  PatchLocationsMiloapisComV1Alpha1LocationClassErrors,
  PatchLocationsMiloapisComV1Alpha1LocationClassResponses,
  PatchLocationsMiloapisComV1Alpha1LocationClassStatusData,
  PatchLocationsMiloapisComV1Alpha1LocationClassStatusErrors,
  PatchLocationsMiloapisComV1Alpha1LocationClassStatusResponses,
  PatchLocationsMiloapisComV1Alpha1LocationData,
  PatchLocationsMiloapisComV1Alpha1LocationErrors,
  PatchLocationsMiloapisComV1Alpha1LocationResponses,
  PatchLocationsMiloapisComV1Alpha1LocationStatusData,
  PatchLocationsMiloapisComV1Alpha1LocationStatusErrors,
  PatchLocationsMiloapisComV1Alpha1LocationStatusResponses,
  PatchLocationsMiloapisComV1Alpha1ServingLocationData,
  PatchLocationsMiloapisComV1Alpha1ServingLocationErrors,
  PatchLocationsMiloapisComV1Alpha1ServingLocationResponses,
  ReadLocationsMiloapisComV1Alpha1LocationClassData,
  ReadLocationsMiloapisComV1Alpha1LocationClassErrors,
  ReadLocationsMiloapisComV1Alpha1LocationClassResponses,
  ReadLocationsMiloapisComV1Alpha1LocationClassStatusData,
  ReadLocationsMiloapisComV1Alpha1LocationClassStatusErrors,
  ReadLocationsMiloapisComV1Alpha1LocationClassStatusResponses,
  ReadLocationsMiloapisComV1Alpha1LocationData,
  ReadLocationsMiloapisComV1Alpha1LocationErrors,
  ReadLocationsMiloapisComV1Alpha1LocationResponses,
  ReadLocationsMiloapisComV1Alpha1LocationStatusData,
  ReadLocationsMiloapisComV1Alpha1LocationStatusErrors,
  ReadLocationsMiloapisComV1Alpha1LocationStatusResponses,
  ReadLocationsMiloapisComV1Alpha1ServingLocationData,
  ReadLocationsMiloapisComV1Alpha1ServingLocationErrors,
  ReadLocationsMiloapisComV1Alpha1ServingLocationResponses,
  ReplaceLocationsMiloapisComV1Alpha1LocationClassData,
  ReplaceLocationsMiloapisComV1Alpha1LocationClassErrors,
  ReplaceLocationsMiloapisComV1Alpha1LocationClassResponses,
  ReplaceLocationsMiloapisComV1Alpha1LocationClassStatusData,
  ReplaceLocationsMiloapisComV1Alpha1LocationClassStatusErrors,
  ReplaceLocationsMiloapisComV1Alpha1LocationClassStatusResponses,
  ReplaceLocationsMiloapisComV1Alpha1LocationData,
  ReplaceLocationsMiloapisComV1Alpha1LocationErrors,
  ReplaceLocationsMiloapisComV1Alpha1LocationResponses,
  ReplaceLocationsMiloapisComV1Alpha1LocationStatusData,
  ReplaceLocationsMiloapisComV1Alpha1LocationStatusErrors,
  ReplaceLocationsMiloapisComV1Alpha1LocationStatusResponses,
  ReplaceLocationsMiloapisComV1Alpha1ServingLocationData,
  ReplaceLocationsMiloapisComV1Alpha1ServingLocationErrors,
  ReplaceLocationsMiloapisComV1Alpha1ServingLocationResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * delete collection of LocationClass
 */
export const deleteLocationsMiloapisComV1Alpha1CollectionLocationClass = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteLocationsMiloapisComV1Alpha1CollectionLocationClassData, ThrowOnError>
): RequestResult<
  DeleteLocationsMiloapisComV1Alpha1CollectionLocationClassResponses,
  DeleteLocationsMiloapisComV1Alpha1CollectionLocationClassErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    DeleteLocationsMiloapisComV1Alpha1CollectionLocationClassResponses,
    DeleteLocationsMiloapisComV1Alpha1CollectionLocationClassErrors,
    ThrowOnError
  >({ url: '/apis/locations.miloapis.com/v1alpha1/locationclasses', ...options });

/**
 * list objects of kind LocationClass
 */
export const listLocationsMiloapisComV1Alpha1LocationClass = <ThrowOnError extends boolean = false>(
  options?: Options<ListLocationsMiloapisComV1Alpha1LocationClassData, ThrowOnError>
): RequestResult<
  ListLocationsMiloapisComV1Alpha1LocationClassResponses,
  ListLocationsMiloapisComV1Alpha1LocationClassErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListLocationsMiloapisComV1Alpha1LocationClassResponses,
    ListLocationsMiloapisComV1Alpha1LocationClassErrors,
    ThrowOnError
  >({ url: '/apis/locations.miloapis.com/v1alpha1/locationclasses', ...options });

/**
 * create a LocationClass
 */
export const createLocationsMiloapisComV1Alpha1LocationClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateLocationsMiloapisComV1Alpha1LocationClassData, ThrowOnError>
): RequestResult<
  CreateLocationsMiloapisComV1Alpha1LocationClassResponses,
  CreateLocationsMiloapisComV1Alpha1LocationClassErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateLocationsMiloapisComV1Alpha1LocationClassResponses,
    CreateLocationsMiloapisComV1Alpha1LocationClassErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locationclasses',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a LocationClass
 */
export const deleteLocationsMiloapisComV1Alpha1LocationClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteLocationsMiloapisComV1Alpha1LocationClassData, ThrowOnError>
): RequestResult<
  DeleteLocationsMiloapisComV1Alpha1LocationClassResponses,
  DeleteLocationsMiloapisComV1Alpha1LocationClassErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteLocationsMiloapisComV1Alpha1LocationClassResponses,
    DeleteLocationsMiloapisComV1Alpha1LocationClassErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locationclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified LocationClass
 */
export const readLocationsMiloapisComV1Alpha1LocationClass = <ThrowOnError extends boolean = false>(
  options: Options<ReadLocationsMiloapisComV1Alpha1LocationClassData, ThrowOnError>
): RequestResult<
  ReadLocationsMiloapisComV1Alpha1LocationClassResponses,
  ReadLocationsMiloapisComV1Alpha1LocationClassErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadLocationsMiloapisComV1Alpha1LocationClassResponses,
    ReadLocationsMiloapisComV1Alpha1LocationClassErrors,
    ThrowOnError
  >({ url: '/apis/locations.miloapis.com/v1alpha1/locationclasses/{name}', ...options });

/**
 * partially update the specified LocationClass
 */
export const patchLocationsMiloapisComV1Alpha1LocationClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchLocationsMiloapisComV1Alpha1LocationClassData, ThrowOnError>
): RequestResult<
  PatchLocationsMiloapisComV1Alpha1LocationClassResponses,
  PatchLocationsMiloapisComV1Alpha1LocationClassErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchLocationsMiloapisComV1Alpha1LocationClassResponses,
    PatchLocationsMiloapisComV1Alpha1LocationClassErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locationclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified LocationClass
 */
export const replaceLocationsMiloapisComV1Alpha1LocationClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceLocationsMiloapisComV1Alpha1LocationClassData, ThrowOnError>
): RequestResult<
  ReplaceLocationsMiloapisComV1Alpha1LocationClassResponses,
  ReplaceLocationsMiloapisComV1Alpha1LocationClassErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceLocationsMiloapisComV1Alpha1LocationClassResponses,
    ReplaceLocationsMiloapisComV1Alpha1LocationClassErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locationclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified LocationClass
 */
export const readLocationsMiloapisComV1Alpha1LocationClassStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadLocationsMiloapisComV1Alpha1LocationClassStatusData, ThrowOnError>
): RequestResult<
  ReadLocationsMiloapisComV1Alpha1LocationClassStatusResponses,
  ReadLocationsMiloapisComV1Alpha1LocationClassStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadLocationsMiloapisComV1Alpha1LocationClassStatusResponses,
    ReadLocationsMiloapisComV1Alpha1LocationClassStatusErrors,
    ThrowOnError
  >({ url: '/apis/locations.miloapis.com/v1alpha1/locationclasses/{name}/status', ...options });

/**
 * partially update status of the specified LocationClass
 */
export const patchLocationsMiloapisComV1Alpha1LocationClassStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchLocationsMiloapisComV1Alpha1LocationClassStatusData, ThrowOnError>
): RequestResult<
  PatchLocationsMiloapisComV1Alpha1LocationClassStatusResponses,
  PatchLocationsMiloapisComV1Alpha1LocationClassStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchLocationsMiloapisComV1Alpha1LocationClassStatusResponses,
    PatchLocationsMiloapisComV1Alpha1LocationClassStatusErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locationclasses/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified LocationClass
 */
export const replaceLocationsMiloapisComV1Alpha1LocationClassStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceLocationsMiloapisComV1Alpha1LocationClassStatusData, ThrowOnError>
): RequestResult<
  ReplaceLocationsMiloapisComV1Alpha1LocationClassStatusResponses,
  ReplaceLocationsMiloapisComV1Alpha1LocationClassStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceLocationsMiloapisComV1Alpha1LocationClassStatusResponses,
    ReplaceLocationsMiloapisComV1Alpha1LocationClassStatusErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locationclasses/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of Location
 */
export const deleteLocationsMiloapisComV1Alpha1CollectionLocation = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteLocationsMiloapisComV1Alpha1CollectionLocationData, ThrowOnError>
): RequestResult<
  DeleteLocationsMiloapisComV1Alpha1CollectionLocationResponses,
  DeleteLocationsMiloapisComV1Alpha1CollectionLocationErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    DeleteLocationsMiloapisComV1Alpha1CollectionLocationResponses,
    DeleteLocationsMiloapisComV1Alpha1CollectionLocationErrors,
    ThrowOnError
  >({ url: '/apis/locations.miloapis.com/v1alpha1/locations', ...options });

/**
 * list objects of kind Location
 */
export const listLocationsMiloapisComV1Alpha1Location = <ThrowOnError extends boolean = false>(
  options?: Options<ListLocationsMiloapisComV1Alpha1LocationData, ThrowOnError>
): RequestResult<
  ListLocationsMiloapisComV1Alpha1LocationResponses,
  ListLocationsMiloapisComV1Alpha1LocationErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListLocationsMiloapisComV1Alpha1LocationResponses,
    ListLocationsMiloapisComV1Alpha1LocationErrors,
    ThrowOnError
  >({ url: '/apis/locations.miloapis.com/v1alpha1/locations', ...options });

/**
 * create a Location
 */
export const createLocationsMiloapisComV1Alpha1Location = <ThrowOnError extends boolean = false>(
  options: Options<CreateLocationsMiloapisComV1Alpha1LocationData, ThrowOnError>
): RequestResult<
  CreateLocationsMiloapisComV1Alpha1LocationResponses,
  CreateLocationsMiloapisComV1Alpha1LocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateLocationsMiloapisComV1Alpha1LocationResponses,
    CreateLocationsMiloapisComV1Alpha1LocationErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Location
 */
export const deleteLocationsMiloapisComV1Alpha1Location = <ThrowOnError extends boolean = false>(
  options: Options<DeleteLocationsMiloapisComV1Alpha1LocationData, ThrowOnError>
): RequestResult<
  DeleteLocationsMiloapisComV1Alpha1LocationResponses,
  DeleteLocationsMiloapisComV1Alpha1LocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteLocationsMiloapisComV1Alpha1LocationResponses,
    DeleteLocationsMiloapisComV1Alpha1LocationErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Location
 */
export const readLocationsMiloapisComV1Alpha1Location = <ThrowOnError extends boolean = false>(
  options: Options<ReadLocationsMiloapisComV1Alpha1LocationData, ThrowOnError>
): RequestResult<
  ReadLocationsMiloapisComV1Alpha1LocationResponses,
  ReadLocationsMiloapisComV1Alpha1LocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadLocationsMiloapisComV1Alpha1LocationResponses,
    ReadLocationsMiloapisComV1Alpha1LocationErrors,
    ThrowOnError
  >({ url: '/apis/locations.miloapis.com/v1alpha1/locations/{name}', ...options });

/**
 * partially update the specified Location
 */
export const patchLocationsMiloapisComV1Alpha1Location = <ThrowOnError extends boolean = false>(
  options: Options<PatchLocationsMiloapisComV1Alpha1LocationData, ThrowOnError>
): RequestResult<
  PatchLocationsMiloapisComV1Alpha1LocationResponses,
  PatchLocationsMiloapisComV1Alpha1LocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchLocationsMiloapisComV1Alpha1LocationResponses,
    PatchLocationsMiloapisComV1Alpha1LocationErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Location
 */
export const replaceLocationsMiloapisComV1Alpha1Location = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceLocationsMiloapisComV1Alpha1LocationData, ThrowOnError>
): RequestResult<
  ReplaceLocationsMiloapisComV1Alpha1LocationResponses,
  ReplaceLocationsMiloapisComV1Alpha1LocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceLocationsMiloapisComV1Alpha1LocationResponses,
    ReplaceLocationsMiloapisComV1Alpha1LocationErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Location
 */
export const readLocationsMiloapisComV1Alpha1LocationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadLocationsMiloapisComV1Alpha1LocationStatusData, ThrowOnError>
): RequestResult<
  ReadLocationsMiloapisComV1Alpha1LocationStatusResponses,
  ReadLocationsMiloapisComV1Alpha1LocationStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadLocationsMiloapisComV1Alpha1LocationStatusResponses,
    ReadLocationsMiloapisComV1Alpha1LocationStatusErrors,
    ThrowOnError
  >({ url: '/apis/locations.miloapis.com/v1alpha1/locations/{name}/status', ...options });

/**
 * partially update status of the specified Location
 */
export const patchLocationsMiloapisComV1Alpha1LocationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchLocationsMiloapisComV1Alpha1LocationStatusData, ThrowOnError>
): RequestResult<
  PatchLocationsMiloapisComV1Alpha1LocationStatusResponses,
  PatchLocationsMiloapisComV1Alpha1LocationStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchLocationsMiloapisComV1Alpha1LocationStatusResponses,
    PatchLocationsMiloapisComV1Alpha1LocationStatusErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Location
 */
export const replaceLocationsMiloapisComV1Alpha1LocationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceLocationsMiloapisComV1Alpha1LocationStatusData, ThrowOnError>
): RequestResult<
  ReplaceLocationsMiloapisComV1Alpha1LocationStatusResponses,
  ReplaceLocationsMiloapisComV1Alpha1LocationStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceLocationsMiloapisComV1Alpha1LocationStatusResponses,
    ReplaceLocationsMiloapisComV1Alpha1LocationStatusErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/locations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of ServingLocation
 */
export const deleteLocationsMiloapisComV1Alpha1CollectionServingLocation = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteLocationsMiloapisComV1Alpha1CollectionServingLocationData, ThrowOnError>
): RequestResult<
  DeleteLocationsMiloapisComV1Alpha1CollectionServingLocationResponses,
  DeleteLocationsMiloapisComV1Alpha1CollectionServingLocationErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    DeleteLocationsMiloapisComV1Alpha1CollectionServingLocationResponses,
    DeleteLocationsMiloapisComV1Alpha1CollectionServingLocationErrors,
    ThrowOnError
  >({ url: '/apis/locations.miloapis.com/v1alpha1/servinglocations', ...options });

/**
 * list objects of kind ServingLocation
 */
export const listLocationsMiloapisComV1Alpha1ServingLocation = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListLocationsMiloapisComV1Alpha1ServingLocationData, ThrowOnError>
): RequestResult<
  ListLocationsMiloapisComV1Alpha1ServingLocationResponses,
  ListLocationsMiloapisComV1Alpha1ServingLocationErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListLocationsMiloapisComV1Alpha1ServingLocationResponses,
    ListLocationsMiloapisComV1Alpha1ServingLocationErrors,
    ThrowOnError
  >({ url: '/apis/locations.miloapis.com/v1alpha1/servinglocations', ...options });

/**
 * create a ServingLocation
 */
export const createLocationsMiloapisComV1Alpha1ServingLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateLocationsMiloapisComV1Alpha1ServingLocationData, ThrowOnError>
): RequestResult<
  CreateLocationsMiloapisComV1Alpha1ServingLocationResponses,
  CreateLocationsMiloapisComV1Alpha1ServingLocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateLocationsMiloapisComV1Alpha1ServingLocationResponses,
    CreateLocationsMiloapisComV1Alpha1ServingLocationErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/servinglocations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a ServingLocation
 */
export const deleteLocationsMiloapisComV1Alpha1ServingLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteLocationsMiloapisComV1Alpha1ServingLocationData, ThrowOnError>
): RequestResult<
  DeleteLocationsMiloapisComV1Alpha1ServingLocationResponses,
  DeleteLocationsMiloapisComV1Alpha1ServingLocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteLocationsMiloapisComV1Alpha1ServingLocationResponses,
    DeleteLocationsMiloapisComV1Alpha1ServingLocationErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/servinglocations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified ServingLocation
 */
export const readLocationsMiloapisComV1Alpha1ServingLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadLocationsMiloapisComV1Alpha1ServingLocationData, ThrowOnError>
): RequestResult<
  ReadLocationsMiloapisComV1Alpha1ServingLocationResponses,
  ReadLocationsMiloapisComV1Alpha1ServingLocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadLocationsMiloapisComV1Alpha1ServingLocationResponses,
    ReadLocationsMiloapisComV1Alpha1ServingLocationErrors,
    ThrowOnError
  >({ url: '/apis/locations.miloapis.com/v1alpha1/servinglocations/{name}', ...options });

/**
 * partially update the specified ServingLocation
 */
export const patchLocationsMiloapisComV1Alpha1ServingLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchLocationsMiloapisComV1Alpha1ServingLocationData, ThrowOnError>
): RequestResult<
  PatchLocationsMiloapisComV1Alpha1ServingLocationResponses,
  PatchLocationsMiloapisComV1Alpha1ServingLocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchLocationsMiloapisComV1Alpha1ServingLocationResponses,
    PatchLocationsMiloapisComV1Alpha1ServingLocationErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/servinglocations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified ServingLocation
 */
export const replaceLocationsMiloapisComV1Alpha1ServingLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceLocationsMiloapisComV1Alpha1ServingLocationData, ThrowOnError>
): RequestResult<
  ReplaceLocationsMiloapisComV1Alpha1ServingLocationResponses,
  ReplaceLocationsMiloapisComV1Alpha1ServingLocationErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceLocationsMiloapisComV1Alpha1ServingLocationResponses,
    ReplaceLocationsMiloapisComV1Alpha1ServingLocationErrors,
    ThrowOnError
  >({
    url: '/apis/locations.miloapis.com/v1alpha1/servinglocations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
