version: '3.8'

services:
  app:
    image: mustela/compas:main
    pull_policy: always
    ports:
      - '4000:4000'
    depends_on:
      - db
      - ollama
    environment:
      - DATABASE_NAME=compas
      - DBHOST=db
      - DBPORT=5432
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - PHX_SERVER=true
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=${DATABASE_URL}
      - VAULT_KEY=${VAULT_KEY}
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
    ports:
      - '5432:5432'
  ollama:
    container_name: ollama_cat
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - 11434
  grafana:
    image: grafana/grafana:9.5.21
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/:/etc/grafana/provisioning/
    env_file:
      - ./docker/grafana/.env
  prometheus:
    image: prom/prometheus:v2.35.0
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  postgres_exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    ports:
      - '9187:9187'
    environment:
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: postgres
      DATA_SOURCE_URI: docker.for.mac.localhost:5432/?sslmode=disable
volumes:
  prometheus-data: {}
  grafana-data: {}
